### ISSUE TITLE
Exception when starting embedded cassandra

### ISSUE THREAD

**Issue by mohitanchlia** [jsevellec/cassandra-unit#103]
I am getting following exception:

java.lang.IllegalAccessError: tried to access method com.google.common.collect.MapMaker.makeComputingMap(Lcom/google/common/base/Function;)Ljava/util/concurrent/ConcurrentMap; from class org.apache.cassandra.service.StorageProxy
Exception encountered during startup: tried to access method com.google.common.collect.MapMaker.makeComputingMap(Lcom/google/common/base/Function;)Ljava/util/concurrent/ConcurrentMap; from class org.apache.cassandra.service.StorageProxy
    at org.apache.cassandra.service.StorageProxy.<clinit>(StorageProxy.java:86)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Unknown Source)
    at org.apache.cassandra.service.StorageService.initServer(StorageService.java:439)
    at org.apache.cassandra.service.StorageService.initServer(StorageService.java:418)
    at org.apache.cassandra.service.AbstractCassandraDaemon.setup(AbstractCassandraDaemon.java:267)
    at org.apache.cassandra.service.AbstractCassandraDaemon.activate(AbstractCassandraDaemon.java:389)
    at org.cassandraunit.utils.EmbeddedCassandraServerHelper$1.run(EmbeddedCassandraServerHelper.java:100)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)

**Comment by DavidRG13** [comment]
@mohitanchlia if this is solved, could you please close this issue?

Thanks a lot
