### ISSUE TITLE
Thrift exception

### ISSUE THREAD

**Issue by mohitanchlia** [jsevellec/cassandra-unit#104]
When I start cassandra in embedded mode I get the following. At this point no request has been sent to Cassandra, just tried to connect to it

12:15:27.435 [Thread-2] INFO  o.a.cassandra.thrift.ThriftServer - Listening for thrift clients...
12:15:28.895 [ScheduledTasks:1] DEBUG o.a.c.service.LoadBroadcaster - Disseminating load info ...
12:15:32.448 [main] INFO  sony.snei.datastore.physical.cassandra.CassandraConnection - Cassandra Properties intialized
12:15:32.458 [main] DEBUG c.d.driver.core.SystemProperties - com.datastax.driver.NEW_NODE_DELAY_SECONDS is undefined, using default value 1
12:15:32.458 [main] DEBUG c.d.driver.core.SystemProperties - com.datastax.driver.NON_BLOCKING_EXECUTOR_SIZE is undefined, using default value 4
12:15:32.629 [main] DEBUG com.datastax.driver.core.Cluster - Starting new cluster with contact points [localhost/127.0.0.1:9171]
12:15:32.699 [main] DEBUG c.d.driver.core.SystemProperties - com.datastax.driver.MAX_SCHEMA_AGREEMENT_WAIT_SECONDS is undefined, using default value 10
12:15:32.789 [Thrift:1] DEBUG o.a.c.thrift.CustomTThreadPoolServer - Thrift transport error occurred during processing of message.
org.apache.thrift.transport.TTransportException: Frame size (33554433) larger than max length (15728640)!
    at org.apache.thrift.transport.TFramedTransport.readFrame(TFramedTransport.java:137) ~[libthrift-0.9.1.jar:0.9.1]
    at org.apache.thrift.transport.TFramedTransport.read(TFramedTransport.java:101) ~[libthrift-0.9.1.jar:0.9.1]
    at org.apache.thrift.transport.TTransport.readAll(TTransport.java:84) ~[libthrift-0.9.1.jar:0.9.1]
    at org.apache.thrift.protocol.TBinaryProtocol.readAll(TBinaryProtocol.java:362) ~[libthrift-0.9.1.jar:0.9.1]
    at org.apache.thrift.protocol.TBinaryProtocol.readI32(TBinaryProtocol.java:284) ~[libthrift-0.9.1.jar:0.9.1]
    at org.apache.thrift.protocol.TBinaryProtocol.readMessageBegin(TBinaryProtocol.java:191) ~[libthrift-0.9.1.jar:0.9.1]
    at org.apache.thrift.TBaseProcessor.process(TBaseProcessor.java:27) ~[libthrift-0.9.1.jar:0.9.1]
    at org.apache.cassandra.thrift.CustomTThreadPoolServer$WorkerProcess.run(CustomTThreadPoolServer.java:201) ~[cassandra-all-2.1.0.jar:2.1.0]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [na:1.7.0_65]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [na:1.7.0_65]
    at java.lang.Thread.run(Unknown Source) [na:1.7.0_65]
12:15:32.789 [New I/O worker #1] DEBUG com.datastax.driver.core.Connection - Connection[localhost/127.0.0.1:9171-1, inFlight=0, closed=true] closing connection

**Comment by jsevellec** [comment]
Closing the issue as the topic is outdated
