### ISSUE TITLE
Exception when shutting down after Testmethod

### ISSUE THREAD

**Issue by goetzingert** [jsevellec/cassandra-unit#109]
I use
<groupId>org.cassandraunit</groupId>
<artifactId>cassandra-unit-spring</artifactId>
<version>2.0.2.2</version>

Test Setup works perfect. The embedded cassandra instance is started. The test runs successful.

The exception occurs in "empty-tests" as well:

@RunWith(SpringJUnit4ClassRunner.class)
@ContextConfiguration(classes = CassandraConfiguration.class, loader = AnnotationConfigContextLoader.class)
@TestExecutionListeners({ CassandraUnitTestExecutionListener.class,
    DependencyInjectionTestExecutionListener.class })
@CassandraUnit
@EmbeddedCassandra(configuration = "cassandra.yaml")
@CassandraDataSet(value = "cassandra_unit_datasets/cassandra_history_table.cql", keyspace = "mjdmhistory")
@Transactional
public class HistoryRepositoryTest {
    @Autowired
    private ApplicationContext context;

```
@Test
public void saveSelectAndDelete() {
    }
```

}

But when shutting down cassandra after the test completes. The following exception occurs:

22:51:42.171 [New I/O worker #1] DEBUG com.datastax.driver.core.Connection - Defuncting connection to /127.0.0.1:9142
com.datastax.driver.core.TransportException: [/127.0.0.1:9142] Channel has been closed
    at com.datastax.driver.core.Connection$Dispatcher.channelClosed(Connection.java:634) [cassandra-driver-core-2.0.4.jar:na]
    at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:88) [netty-3.9.0.Final.jar:na]
    at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [netty-3.9.0.Final.jar:na]
    at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791) [netty-3.9.0.Final.jar:na]
    at org.jboss.netty.handler.codec.oneone.OneToOneDecoder.handleUpstream(OneToOneDecoder.java:60) [netty-3.9.0.Final.jar:na]
    at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [netty-3.9.0.Final.jar:na]
    at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791) [netty-3.9.0.Final.jar:na]
    at org.jboss.netty.handler.codec.frame.FrameDecoder.cleanup(FrameDecoder.java:493) [netty-3.9.0.Final.jar:na]
    at org.jboss.netty.handler.codec.frame.FrameDecoder.channelClosed(FrameDecoder.java:371) [netty-3.9.0.Final.jar:na]
    at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:88) [netty-3.9.0.Final.jar:na]
    at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [netty-3.9.0.Final.jar:na]
    at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559) [netty-3.9.0.Final.jar:na]
    at org.jboss.netty.channel.Channels.fireChannelClosed(Channels.java:468) [netty-3.9.0.Final.jar:na]
    at org.jboss.netty.channel.socket.nio.AbstractNioWorker.close(AbstractNioWorker.java:375) [netty-3.9.0.Final.jar:na]
    at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:93) [netty-3.9.0.Final.jar:na]
    at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108) [netty-3.9.0.Final.jar:na]
    at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:318) [netty-3.9.0.Final.jar:na]
    at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89) [netty-3.9.0.Final.jar:na]
    at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178) [netty-3.9.0.Final.jar:na]
    at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108) [netty-3.9.0.Final.jar:na]
    at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42) [netty-3.9.0.Final.jar:na]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110) [na:1.7.0_12-ea]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603) [na:1.7.0_12-ea]
    at java.lang.Thread.run(Thread.java:722) [na:1.7.0_12-ea]

Seems like the connection pool has not been shutting down before server terminates.

Unfortunatly I cannot add the Full Stacktrace because of restrictions due to the issue description size and .txt attachments are not supported.

**Comment by boneill42** [comment]
You need to call close() on the cluster. You can drop this in a tearDown method like this:

    @After
    public void tearDown() throws InterruptedException{        
        LOG.debug("Tearing Down.");
        cqlUnit.cluster.close();
    }

**Comment by justinhrobbins** [comment]
I am seeing the same issue.

@boneill42, in the cassandra-unit-spring scenario how would we call cqlUnit.cluster.close()?  It seems the TestExecutionListener should be performing any necessary cleanup.

**Comment by boneill42** [comment]
Agreed.  We aren't using the spring version, so we have direct access to the cluster object.

I took a quick look, and it appears as though it should go here:
https://github.com/jsevellec/cassandra-unit/blob/master/cassandra-unit-spring/src/main/java/org/cassandraunit/spring/AbstractCassandraUnitTestExecutionListener.java#L102-L104

The cluster object appears to be available here:
https://github.com/jsevellec/cassandra-unit/blob/master/cassandra-unit-spring/src/main/java/org/cassandraunit/spring/AbstractCassandraUnitTestExecutionListener.java#L60-L61

So, in theory, maybe you can save the cluster off in a member variable, then call cluster.close() in the cleanServer method.  I don't have time to give it a try, but that might work.

**Comment by prakhar0104** [comment]
I am seeing the same issue as above.
@boneill42 
Can you please help !!

**Comment by jsevellec** [comment]
The problem is already existing while running the test suite (with maven for instance) on the cassandra-unit project itself. It's not specific to the cassandra-unit-spring part. I'm trying to fix that but to be transparent, at the moment, i don't have a lot of free space to investigate this problem... any help would be appreciated...

**Comment by jsevellec** [comment]
Reported against cassandra-unit-spring 2.0.2.2, which is many majors old. Shutdown handling has changed substantially since — see #311 for the current state. If this still occurs on 5.0.0, please add the stack trace and I will reopen the investigation.

Keeping this open. (Triage pass after the Cassandra 5.0 / JDK 17 modernization, #345.)

**Comment by jsevellec** [comment]
Closing as not reproducible. The trace is driver 2.0.4 on Netty 3 from cassandra-unit-spring 2.0.2.2: a per-test connection pool outliving the server on shutdown. The driver is now 4.x, and there is one shared session per JVM closed by a shutdown hook rather than one pool per test (see #161), so this code path no longer exists. If you see something similar on 5.x, please open a new issue with the stack trace.
