### ISSUE TITLE
Intermittent Cassandra connection failures

### ISSUE THREAD

**Issue by mkaberman** [jsevellec/cassandra-unit#110]
I am observing strange behavior with my unit tests: on some hosts the tests intermittently are unable to connect to embedded Cassandra instance. I made sure that nothing on the hosts is using port 9142 or other Cassandra ports. The exception I am getting is :

:07:06:51.981 [pool-1-thread-1] WARN  org.apache.cassandra.utils.CLibrary - Unable to lock JVM memory (ENOMEM). This can result in part of the JVM being swapped out, especially with mmapped I/O enabled. Increase RLIMIT_MEMLOCK or run Cassandra as root.
07:06:52.010 [pool-1-thread-1] INFO  o.a.cassandra.service.CacheService - Initializing key cache with capacity of 5 MBs.
07:06:52.041 [pool-1-thread-1] INFO  o.a.cassandra.service.CacheService - Initializing row cache with capacity of 0 MBs
07:06:52.055 [pool-1-thread-1] INFO  o.a.cassandra.service.CacheService - Initializing counter cache with capacity of 2 MBs
07:06:52.058 [pool-1-thread-1] INFO  o.a.cassandra.service.CacheService - Scheduling counter cache save to every 7200 seconds (going to save all keys).
07:06:52.183 [pool-1-thread-1] INFO  o.a.cassandra.db.ColumnFamilyStore - Initializing system.sstable_activity
07:07:02.798 [main] ERROR o.s.test.context.TestContextManager - Caught exception while allowing TestExecutionListener [org.cassandraunit.spring.CassandraUnitDependencyInjectionTestExecutionListener@68c9d179] to prepare test instance [com.emc.brs.discovery.persistence.ManagementDevicePersistenceHandlerTest@2416c658]
com.datastax.driver.core.exceptions.NoHostAvailableException: All host(s) tried for query failed (tried: /127.0.0.1:9142 (com.datastax.driver.core.TransportException: [/127.0.0.1:9142] Cannot connect))
    at com.datastax.driver.core.ControlConnection.reconnectInternal(ControlConnection.java:220) ~[cassandra-driver-core-2.1.3.jar:na]
    at com.datastax.driver.core.ControlConnection.connect(ControlConnection.java:78) ~[cassandra-driver-core-2.1.3.jar:na]
    at com.datastax.driver.core.Cluster$Manager.init(Cluster.java:1231) ~[cassandra-driver-core-2.1.3.jar:na]
    at com.datastax.driver.core.Cluster.init(Cluster.java:158) ~[cassandra-driver-core-2.1.3.jar:na]
    at com.datastax.driver.core.Cluster.connect(Cluster.java:246) ~[cassandra-driver-core-2.1.3.jar:na]
    at org.cassandraunit.spring.AbstractCassandraUnitTestExecutionListener.startServer(AbstractCassandraUnitTestExecutionListener.java:61) ~[cassandra-unit-spring-2.0.2.2.jar:na]
    at org.cassandraunit.spring.CassandraUnitDependencyInjectionTestExecutionListener.prepareTestInstance(CassandraUnitDependencyInjectionTestExecutionListener.java:21) ~[cassandra-unit-spring-2.0.2.2.jar:na]
    at org.springframework.test.context.TestContextManager.prepareTestInstance(TestContextManager.java:212) ~[spring-test-4.1.1.RELEASE.jar:4.1.1.RELEASE]
    at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.createTest(SpringJUnit4ClassRunner.java:199) [spring-test-4.1.1.RELEASE.jar:4.1.1.RELEASE]
    at org.springframework.test.context.junit4.SpringJUnit4ClassRunner$1.runReflectiveCall(SpringJUnit4ClassRunner.java:251) [spring-test-4.1.1.RELEASE.jar:4.1.1.RELEASE]
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12) [junit-4.11.jar:na]
    at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.methodBlock(SpringJUnit4ClassRunner.java:253) [spring-test-4.1.1.RELEASE.jar:4.1.1.RELEASE]
    at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:216) [spring-test-4.1.1.RELEASE.jar:4.1.1.RELEASE]
    at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:82) [spring-test-4.1.1.RELEASE.jar:4.1.1.RELEASE]
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238) [junit-4.11.jar:na]
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63) [junit-4.11.jar:na]
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236) [junit-4.11.jar:na]
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53) [junit-4.11.jar:na]
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229) [junit-4.11.jar:na]
    at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26) [junit-4.11.jar:na]
    at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:60) [spring-test-4.1.1.RELEASE.jar:4.1.1.RELEASE]
    at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:67) [spring-test-4.1.1.RELEASE.jar:4.1.1.RELEASE]
    at org.junit.runners.ParentRunner.run(ParentRunner.java:309) [junit-4.11.jar:na]
    at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:162) [spring-test-4.1.1.RELEASE.jar:4.1.1.RELEASE]
    at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:283) [surefire-junit4-2.18.1.jar:2.18.1]
    at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:173) [surefire-junit4-2.18.1.jar:2.18.1]
    at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153) [surefire-junit4-2.18.1.jar:2.18.1]
    at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:128) [surefire-junit4-2.18.1.jar:2.18.1]
    at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203) [surefire-booter-2.18.1.jar:2.18.1]
    at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155) [surefire-booter-2.18.1.jar:2.18.1]
    at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103) [surefire-booter-2.18.1.jar:2.18.1]

My unit tests are annotated like this:
@RunWith(SpringJUnit4ClassRunner.class)
@ContextConfiguration(classes = { CassandraTestSession.class, CassandraConfig.class, DiscoveryCredentialsPersistenceHandler.class, QueryCache.class }, loader = AnnotationConfigContextLoader.class)
@TestExecutionListeners({ CassandraUnitDependencyInjectionTestExecutionListener.class, DependencyInjectionTestExecutionListener.class, DirtiesContextTestExecutionListener.class })
@CassandraDataSet(value = { "create_discovery_tables.cql", "populate_credentials.cql" }, keyspace = "polariskeyspace")
@EmbeddedCassandra
@DirtiesContext(classMode = AFTER_CLASS)

and I am using embedded Cassandra ver.2.1.0

I am wondering if anyone encountered this kind of intermittent failures before and if there is a way to get rid of it.

**Comment by PierreVincent** [comment]
I'm getting similar intermittent errors:
```
java.io.IOException: Failed to open native connection to Cassandra at {127.0.0.1}:9042
...
Cause: com.datastax.driver.core.exceptions.NoHostAvailableException: All host(s) tried for query failed (tried: /127.0.0.1:9042 (com.datastax.driver.core.TransportException: [/127.0.0.1:9042] Cannot connect))
```

These are happening with Cassandra-Unit 2.0.2.1 and 2.0.2.2

**Comment by PierreVincent** [comment]
I've only experienced this problem on my CI environment, so it's likely that the 10 seconds timeout is too short in some cases (especially if there are multiple builds running simultaneously). 

It looks like https://github.com/jsevellec/cassandra-unit/pull/89 might be a way to sort this out. From 2.0.2.2 it's now possible specify another timeout for the EmbeddedCassandra startup.

**Comment by PierreVincent** [comment]
Sorry it's been a while but coming back to confirm than upgrading to 2.0.2.2 and starting the Cassandra server using the following code has sorted out the random connection failures I was getting on my build server.

```
EmbeddedCassandraServerHelper.startEmbeddedCassandra(20000L)
```

 This will increase the startup timeout to 20s (instead of 10s default).

**Comment by sireeshal** [comment]
I am running into the same issue. Increasing timeout didn't help in my case. How to check what version of being used in Embedcassandra? I have 2.0.10 and 2.1.0 versions of cassandra installed locally.

**Comment by ukjbrown** [comment]
@sireeshal did you ever resolve this issue in your build? Increasing the timeout has also not resolved intermittent failures for me.

**Comment by jsebrien** [comment]
not for me either

**Comment by sateeshpnv** [comment]
Is this issue resolved for anyone? If so, how?

On some bad days, it fails 9 out of 10 times.
