### ISSUE TITLE
Getting Exception with datastax driver

### ISSUE THREAD

**Issue by sougatabh** [jsevellec/cassandra-unit#140]
Below is the Exception I am getting, could you please help.

17:19:12.378 [Native-Transport-Requests:10] WARN  o.apache.cassandra.utils.FBUtilities - Trigger directory doesn't exist, please create it and try again.
17:19:12.379 [Native-Transport-Requests:10] DEBUG o.a.c.l.AbstractReplicationStrategy - clearing cached endpoints
17:19:12.385 [Native-Transport-Requests:10] DEBUG org.apache.cassandra.tracing.Tracing - request complete
17:19:12.385 [Native-Transport-Requests:10] DEBUG o.apache.cassandra.transport.Message - Responding: EMPTY RESULT, v=2
17:19:12.386 [main] DEBUG c.a.a.d.d.u.i.RawTransactionDAOImpl - KPI Data is stored successfully!!!
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 13.176 sec - in com.appnomic.appsone.dataservice.services.db.KPIMessageDBServiceTest
Running com.appnomic.appsone.dataservice.services.db.HttpTransactionDBServiceTest
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.047 sec - in com.appnomic.appsone.dataservice.services.db.HttpTransactionDBServiceTest
Running com.appnomic.appsone.dataservice.services.db.TransactionDBServiceTest
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.018 sec - in com.appnomic.appsone.dataservice.services.db.TransactionDBServiceTest
Running com.appnomic.appsone.dataservice.services.db.EnterpriseDBServiceTest
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.025 sec - in com.appnomic.appsone.dataservice.services.db.EnterpriseDBServiceTest
Running com.appnomic.appsone.dataservice.services.db.PSAgentDBServiceTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.015 sec - in com.appnomic.appsone.dataservice.services.db.PSAgentDBServiceTest
17:19:12.495 [StorageServiceShutdownHook] INFO  o.a.cassandra.thrift.ThriftServer - Stop listening to thrift clients
17:19:12.505 [New I/O worker #2] DEBUG com.datastax.driver.core.Connection - Defuncting connection to /127.0.0.1:9142
com.datastax.driver.core.TransportException: [/127.0.0.1:9142] Channel has been closed
	at com.datastax.driver.core.Connection$Dispatcher.channelClosed(Connection.java:750) [cassandra-driver-core-2.1.4.jar:na]
	at com.datastax.shaded.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:88) [cassandra-driver-core-2.1.4.jar:na]
	at com.datastax.shaded.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [cassandra-driver-core-2.1.4.jar:na]
	at com.datastax.shaded.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791) [cassandra-driver-core-2.1.4.jar:na]
	at com.datastax.shaded.netty.handler.codec.oneone.OneToOneDecoder.handleUpstream(OneToOneDecoder.java:60) [cassandra-driver-core-2.1.4.jar:na]
	at com.datastax.shaded.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [cassandra-driver-core-2.1.4.jar:na]
	at com.datastax.shaded.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791) [cassandra-driver-core-2.1.4.jar:na]
	at com.datastax.shaded.netty.handler.codec.frame.FrameDecoder.cleanup(FrameDecoder.java:493) [cassandra-driver-core-2.1.4.jar:na]
	at com.datastax.shaded.netty.handler.codec.frame.FrameDecoder.channelClosed(FrameDecoder.java:371) [cassandra-driver-core-2.1.4.jar:na]
	at com.datastax.shaded.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:88) [cassandra-driver-core-2.1.4.jar:na]
	at com.datastax.shaded.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [cassandra-driver-core-2.1.4.jar:na]
	at com.datastax.shaded.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559) [cassandra-driver-core-2.1.4.jar:na]
	at com.datastax.shaded.netty.channel.Channels.fireChannelClosed(Channels.java:468) [cassandra-driver-core-2.1.4.jar:na]
	at com.datastax.shaded.netty.channel.socket.nio.AbstractNioWorker.close(AbstractNioWorker.java:375) [cassandra-driver-core-2.1.4.jar:na]
	at com.datastax.shaded.netty.channel.socket.nio.NioWorker.read(NioWorker.java:93) [cassandra-driver-core-2.1.4.jar:na]
	at com.datastax.shaded.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108) [cassandra-driver-core-2.1.4.jar:na]
	at com.datastax.shaded.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:318) [cassandra-driver-core-2.1.4.jar:na]
	at com.datastax.shaded.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89) [cassandra-driver-core-2.1.4.jar:na]
	at com.datastax.shaded.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178) [cassandra-driver-core-2.1.4.jar:na]
	at com.datastax.shaded.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108) [cassandra-driver-core-2.1.4.jar:na]
	at com.datastax.shaded.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42) [cassandra-driver-core-2.1.4.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_60]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_60]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_60]

**Comment by jsevellec** [comment]
is it making your test failing or is it just a log?

**Comment by leomrocha** [comment]
Same issue here, It's making the test fail.

Here the logs:
    [Hector.me.prettyprint.cassandra.connection.CassandraHostRetryService-1] INFO  m.p.c.connection.HConnectionManager - Added host localhost(127.0.0.1):9171 to pool
    15:47:20.501 [specs2.fixed.env-351641755-1] DEBUG m.p.c.c.client.HThriftClient - keyspace reseting from null to cassakeyspace
    15:47:20.567 [Thrift:4] DEBUG o.a.cassandra.thrift.CassandraServer - batch_mutate
    15:47:20.648 [Thrift:4] WARN  o.apache.cassandra.utils.FBUtilities - Trigger directory doesn't exist, please create it and try again.
    15:47:20.660 [Thrift:4] DEBUG o.a.c.l.AbstractReplicationStrategy - clearing cached endpoints
    15:47:20.720 [Thrift:4] DEBUG org.apache.cassandra.tracing.Tracing - request complete
    15:47:20.744 [specs2.fixed.env-351641755-1] DEBUG m.p.c.c.client.HThriftClient - keyspace reseting from null to cassakeyspace
    15:47:20.750 [Thrift:8] DEBUG o.a.cassandra.thrift.CassandraServer - batch_mutate
    15:47:20.775 [Thrift:8] DEBUG org.apache.cassandra.tracing.Tracing - request complete
    [info] MYTEST
    [info] 
    [info] The 'mytest' method in MYTEST object  should
    [error]   ! Create MYTEST class instance 
    [error]    me.prettyprint.hector.api.exceptions.HectorTransportException: org.apache.thrift.transport.TTransportException (ExceptionsTranslatorImpl.java:39)
    [error] me.prettyprint.cassandra.service.ExceptionsTranslatorImpl.translate(ExceptionsTranslatorImpl.java:39)
    [error] me.prettyprint.cassandra.service.ThriftCluster$6.execute(ThriftCluster.java:164)
    [error] me.prettyprint.cassandra.service.ThriftCluster$6.execute(ThriftCluster.java:151)
    [error] me.prettyprint.cassandra.service.Operation.executeAndSetResult(Operation.java:104)

**Comment by sougatabh** [comment]
For me test is passed but, feel query is not getting executed.

**Comment by gayetri** [comment]
Any updates on this? I have the same issue and my insert statement is not getting executed too.

**Comment by gayetri** [comment]
I see the same warning in the logs, the database operations are not affected though.

**Comment by MALPI** [comment]
Actually It doesn't seem to be a real issue? Can it be closed?
