### ISSUE TITLE
Using in SBT

### ISSUE THREAD

**Issue by cranst0n** [jsevellec/cassandra-unit#149]
I'm trying to use cassandra-unit within SBT and I have a simple test working with one issue. Here's a stripped down version of my test code:

```scala
class CassandraSpec extends Specification with Loggable {

  sequential

  trait CassandraUnitTest extends After {

    EmbeddedCassandraServerHelper.startEmbeddedCassandra()

    def after = {
      EmbeddedCassandraServerHelper.cleanEmbeddedCassandra()
    }
  }

  "A Cassandra" should {

    "do something" in new CassandraUnitTest {
      1 + 1 must be equalTo 2
    }

    "do something else" in new CassandraUnitTest {
      2 + 2 must be equalTo 4
    }

  }
```

When I run `test` within SBT the tests pass and it drops me back to the SBT prompt. I can tell that the embedded cassandra daemon is still running after the test completes via `netstat -ltn` as I can see ports 9142, 7010 and 9171 are open. When I exit SBT, those ports are closed and I see log output about Cassandra shutting down.

The problem arises when I try to run `test` again without restarting SBT. It seems as though `EmbeddedCassandraServerHelper` forgets that the embedded instance is still running because it attempts to start another instance and I get the following exception (with cassandra-unit debug logging turned on):

```
DEBUG o.c.u.EmbeddedCassandraServerHelper - Starting cassandra...
DEBUG o.c.u.EmbeddedCassandraServerHelper - Initialization needed
javax.management.InstanceAlreadyExistsException: org.apache.cassandra.db:type=DynamicEndpointSnitch
Fatal error during configuration loading; unable to start. See log for stacktrace.ERROR o.a.c.config.DatabaseDescriptor - Fatal error during configuration loading
java.lang.RuntimeException: javax.management.InstanceAlreadyExistsException: org.apache.cassandra.db:type=DynamicEndpointSnitch
	at org.apache.cassandra.locator.DynamicEndpointSnitch.registerMBean(DynamicEndpointSnitch.java:102) ~[cassandra-all-2.1.9.jar:2.1.9]
	at org.apache.cassandra.locator.DynamicEndpointSnitch.<init>(DynamicEndpointSnitch.java:90) ~[cassandra-all-2.1.9.jar:2.1.9]
	at org.apache.cassandra.locator.DynamicEndpointSnitch.<init>(DynamicEndpointSnitch.java:64) ~[cassandra-all-2.1.9.jar:2.1.9]
	at org.apache.cassandra.config.DatabaseDescriptor.createEndpointSnitch(DatabaseDescriptor.java:663) ~[cassandra-all-2.1.9.jar:2.1.9]
	at org.apache.cassandra.config.DatabaseDescriptor.applyConfig(DatabaseDescriptor.java:459) ~[cassandra-all-2.1.9.jar:2.1.9]
	at org.apache.cassandra.config.DatabaseDescriptor.<clinit>(DatabaseDescriptor.java:136) ~[cassandra-all-2.1.9.jar:2.1.9]
	at org.cassandraunit.utils.EmbeddedCassandraServerHelper.mkdirs(EmbeddedCassandraServerHelper.java:334) [cassandra-unit-2.1.9.2.jar:na]
	at org.cassandraunit.utils.EmbeddedCassandraServerHelper.cleanupAndLeaveDirs(EmbeddedCassandraServerHelper.java:305) [cassandra-unit-2.1.9.2.jar:na]
	at org.cassandraunit.utils.EmbeddedCassandraServerHelper.startEmbeddedCassandra(EmbeddedCassandraServerHelper.java:116) [cassandra-unit-2.1.9.2.jar:na]
	at org.cassandraunit.utils.EmbeddedCassandraServerHelper.startEmbeddedCassandra(EmbeddedCassandraServerHelper.java:85) [cassandra-unit-2.1.9.2.jar:na]
Caused by: javax.management.InstanceAlreadyExistsException: org.apache.cassandra.db:type=DynamicEndpointSnitch
	at com.sun.jmx.mbeanserver.Repository.addMBean(Repository.java:437) ~[na:1.8.0_60]
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerWithRepository(DefaultMBeanServerInterceptor.java:1898) ~[na:1.8.0_60]
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerDynamicMBean(DefaultMBeanServerInterceptor.java:966) ~[na:1.8.0_60]
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerObject(DefaultMBeanServerInterceptor.java:900) ~[na:1.8.0_60]
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerMBean(DefaultMBeanServerInterceptor.java:324) ~[na:1.8.0_60]
	at com.sun.jmx.mbeanserver.JmxMBeanServer.registerMBean(JmxMBeanServer.java:522) ~[na:1.8.0_60]
	at org.apache.cassandra.locator.DynamicEndpointSnitch.registerMBean(DynamicEndpointSnitch.java:98) ~[cassandra-all-2.1.9.jar:2.1.9]
	at org.apache.cassandra.locator.DynamicEndpointSnitch.<init>(DynamicEndpointSnitch.java:90) ~[cassandra-all-2.1.9.jar:2.1.9]
	at org.apache.cassandra.locator.DynamicEndpointSnitch.<init>(DynamicEndpointSnitch.java:64) ~[cassandra-all-2.1.9.jar:2.1.9]
	at org.apache.cassandra.config.DatabaseDescriptor.createEndpointSnitch(DatabaseDescriptor.java:663) ~[cassandra-all-2.1.9.jar:2.1.9]
```

Maybe this is an issue specific the running within SBT? I've tried running so SBT will fork the test process in the hopes that may trigger the shutdown after the test task completes but it doesn't seem to help.

**Comment by cranst0n** [comment]
Turns out I had a typo in my SBT config file and forking was the answer to this problem. Adding the following to my build definition resolves the issue:

```
fork in Test := true
```

**Comment by NicolaeNMV** [comment]
Have the same problem. Thanks for posting a workaround.

**Comment by edwmurph** [comment]
The above workaround is not working for me and I'm seeing this same exact issue with the following:
```
sbt: 1.2.6
cassandra-unit: 3.1.3.2
javax.ws.rs-api: 2.1-m09
```

And I'm also seeing the following logs:
```
[error] java.lang.ExceptionInInitializerError
[error] 	at org.apache.cassandra.config.DatabaseDescriptor.<clinit>(DatabaseDescriptor.java:130)
...
[error] Caused by: java.lang.RuntimeException: javax.management.InstanceAlreadyExistsException: org.apache.cassandra.db:type=DynamicEndpointSnitch
...
[error] Caused by: javax.management.InstanceAlreadyExistsException: org.apache.cassandra.db:type=DynamicEndpointSnitch
...
```
Any ideas?

**Comment by vasigorc** [comment]
Same as above:
```scala
sbt: 1.3.6
cassandra-unit: 3.11.2.0
```

```shell
[info]   ...
[info]   Cause: javax.management.InstanceAlreadyExistsException: org.apache.cassandra.db:type=DynamicEndpointSnitch
[info]   at com.sun.jmx.mbeanserver.Repository.addMBean(Repository.java:437)
[info]   at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerWithRepository(DefaultMBeanServerInterceptor.java:1898)
[info]   at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerDynamicMBean(DefaultMBeanServerInterceptor.java:966)
[info]   at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerObject(DefaultMBeanServerInterceptor.java:900)
[info]   at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerMBean(DefaultMBeanServerInterceptor.java:324)
[info]   at com.sun.jmx.mbeanserver.JmxMBeanServer.registerMBean(JmxMBeanServer.java:522)
[info]   at org.apache.cassandra.utils.MBeanWrapper$PlatformMBeanWrapper.registerMBean(MBeanWrapper.java:108)
[info]   at org.apache.cassandra.utils.MBeanWrapper.registerMBean(MBeanWrapper.java:52)
[info]   at org.apache.cassandra.locator.DynamicEndpointSnitch.registerMBean(DynamicEndpointSnitch.java:142)
[info]   at org.apache.cassandra.locator.DynamicEndpointSnitch.<init>(DynamicEndpointSnitch.java:107)
```
