### ISSUE TITLE
java.lang.NoSuchMethodError: com.codahale.metrics.Snapshot: method <init>()V not found

### ISSUE THREAD

**Issue by mamghari** [jsevellec/cassandra-unit#165]
Hi,

I have some issues with my Cassandra Unit Tests, could you please help ?
I am not using Spring, and don't want to use it. I exclude nothing, just added the dependencies. It is really annoying. May be there is a manner to deactivate the metrics ?

My cassandra unit version is as following:
```
<com.datastax.cassandra.version>2.1.8</com.datastax.cassandra.version>
<cassandra-unit-version>2.2.2.1</cassandra-unit-version>
..
		<dependency>
			<groupId>org.cassandraunit</groupId>
			<artifactId>cassandra-unit</artifactId>
			<version>${cassandra-unit-version}</version>
			<scope>test</scope>
		</dependency>
```
StackTrace :
[2016-01-11 15:37:31] -  INFO Cluster:1460 [main] New Cassandra host localhost/127.0.0.1:9142 added
[2016-01-11 15:37:37] - ERROR CassandraDaemon:185 [OptionalTasks:1] Exception in thread Thread[OptionalTasks:1,5,main]
java.lang.NoSuchMethodError: com.codahale.metrics.Snapshot: method <init>()V not found
	at com.codahale.metrics.UniformSnapshot.<init>(UniformSnapshot.java:39)
	at org.apache.cassandra.metrics.EstimatedHistogramReservoir$HistogramSnapshot.<init>(EstimatedHistogramReservoir.java:77)
	at org.apache.cassandra.metrics.EstimatedHistogramReservoir.getSnapshot(EstimatedHistogramReservoir.java:62)
	at com.codahale.metrics.Histogram.getSnapshot(Histogram.java:54)
	at com.codahale.metrics.Timer.getSnapshot(Timer.java:142)
	at org.apache.cassandra.db.ColumnFamilyStore$3.run(ColumnFamilyStore.java:435)
	at org.apache.cassandra.concurrent.DebuggableScheduledThreadPoolExecutor$UncomplainingRunnable.run(DebuggableScheduledThreadPoolExecutor.java:118)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)

**Comment by OrangeDog** [comment]
Problem is probably that com.codahale.metrics:metrics-core used by cassandra-driver-core is conflicting with io.dropwizard.metrics:metrics-core used by cassandra-all.

I don't know whose smart idea it was to change the groupid but not the classes' package...

Related: #107

**Comment by lzvtrifork** [comment]
It does seem to work if you force dependency replacement, and only use io.dropwizard.metrics:metrics-core, but I have no idea of how different the API is, so that is probably a runtime exception waiting to happen.

I think the right solution is to upgrade to Cassandra driver 3.0, which also uses io.dropwizard.metrics:metrics-core, because they plan on obsoleting all other drivers anyway. Although it is not a drop-in replacement and requires some code rewrites.

**Comment by OrangeDog** [comment]
That's why I'm doing it with classpath ordering, so it only affects tests and not runtime.

Problem with the driver upgrade is the breaking changes, and Spring hasn't been updated for them yet.

**Comment by mamghari** [comment]
As solution, I forced the dependency to 
```
<metrics.version>3.1.0</metrics.version>
<dependency>
				<groupId>io.dropwizard.metrics</groupId>
				<artifactId>metrics-core</artifactId>
				<version>${metrics.version}</version>
			</dependency>
```
Now it works well. So it means that this version is now used as library by Maven.

It seems that Maven didn't manage well this, may be because of the change of groupId.

Thank you for your answers.
