### ISSUE TITLE
Embedded Cassandra stalls after ~7 minutes

### ISSUE THREAD

**Issue by kasabov** [jsevellec/cassandra-unit#181]
I'm having a problem with embedded Cassandra not accepting connections after ~7 minutes. Here's a simple unit test to reproduce the issue:

``` java
package net.company;
import com.datastax.driver.core.Cluster;
import com.datastax.driver.core.Session;
import org.apache.thrift.transport.TTransportException;
import org.cassandraunit.utils.EmbeddedCassandraServerHelper;
import org.junit.Test;

import java.io.IOException;

public class CassandraIntegrationTest {

    @Test
    public void testMe() throws InterruptedException, IOException, TTransportException {
        EmbeddedCassandraServerHelper.startEmbeddedCassandra();
        try {
            Cluster cluster = Cluster.builder()
                    .addContactPoints("127.0.0.1")
                    .withPort(9142) // TODO Use random port
                    .withoutMetrics()
                    .build();

            for (int i = 0; i < 10; i++) {
                Session session = cluster.connect();
                System.err.println(
                        session.execute("select release_version from system.local").
                                one().getString("release_version")
                );

                System.err.println(String.format("(%d) Sleeping for 1m...", i));
                Thread.sleep(60 * 1000);
            }
        } finally {
            EmbeddedCassandraServerHelper.cleanEmbeddedCassandra();
        }
    }
}
```

Output:

```
3.5
(0) Sleeping for 1m...
3.5
(1) Sleeping for 1m...
3.5
(2) Sleeping for 1m...
3.5
(3) Sleeping for 1m...
3.5
(4) Sleeping for 1m...
3.5
(5) Sleeping for 1m...
3.5
(6) Sleeping for 1m...
2016-07-08 13:14:32,992 ERROR   [] [cluster1-reconnection-0] com.datastax.driver.core.ControlConnection : [Control connection] Cannot connect to any host, scheduling retry in 1000 milliseconds
2016-07-08 13:14:46,087 ERROR   [] [cluster1-reconnection-0] com.datastax.driver.core.ControlConnection : [Control connection] Cannot connect to any host, scheduling retry in 2000 milliseconds
2016-07-08 13:14:48,087 ERROR   [] [cluster1-reconnection-0] com.datastax.driver.core.ControlConnection : [Control connection] Cannot connect to any host, scheduling retry in 4000 milliseconds

com.datastax.driver.core.exceptions.NoHostAvailableException: All host(s) tried for query failed (tried: localhost/0:0:0:0:0:0:0:1:9142 (com.datastax.driver.core.exceptions.TransportException: [localhost/0:0:0:0:0:0:0:1] Cannot connect), localhost/127.0.0.1:9142 (com.datastax.driver.core.exceptions.OperationTimedOutException: [localhost/127.0.0.1] Operation timed out))

    at com.datastax.driver.core.ControlConnection.reconnectInternal(ControlConnection.java:233)
    at com.datastax.driver.core.ControlConnection.connect(ControlConnection.java:79)
    at com.datastax.driver.core.Cluster$Manager.init(Cluster.java:1424)
    at com.datastax.driver.core.Cluster.init(Cluster.java:163)
    at com.datastax.driver.core.Cluster.connectAsync(Cluster.java:334)
    at com.datastax.driver.core.Cluster.connectAsync(Cluster.java:309)
    at com.datastax.driver.core.Cluster.connect(Cluster.java:251)
    at org.cassandraunit.utils.EmbeddedCassandraServerHelper.dropKeyspacesWithNativeDriver(EmbeddedCassandraServerHelper.java:245)
    at org.cassandraunit.utils.EmbeddedCassandraServerHelper.dropKeyspaces(EmbeddedCassandraServerHelper.java:207)
    at org.cassandraunit.utils.EmbeddedCassandraServerHelper.cleanEmbeddedCassandra(EmbeddedCassandraServerHelper.java:164)
    at net.company.testMe(CassandraIntegrationTest.java:35)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
    at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
    at org.junit.runners.Suite.runChild(Suite.java:128)
    at org.junit.runners.Suite.runChild(Suite.java:27)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
    at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
    at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:119)
    at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:42)
    at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:234)
    at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:74)
```

Enabling TRACE levels doesn't provide any clues. The Cassandra instance is up and running (JMX connection works), however, all new connections are refused and I also see a few CLOSE_WAIT connections. Additionally, the unit test never completes.
Any hints for resolving this issue are welcome.

**Comment by xiaodong-xie** [comment]
Have you tried reusing `session`? I meant not to connect to cluster for session anytime you want one...

**Comment by dprao** [comment]
I am facing the same issue.  Any solution? or why is it happening?

**Comment by phalodi** [comment]
I also  facing same problem. Anyone find any solution?

**Comment by jsevellec** [comment]
Still open, no reproduction. A stall after several minutes suggests either the commitlog/disk checks or a resource limit rather than a plain bug. If it still happens on 5.0.0 a thread dump at the point of the stall would be the useful thing.

Keeping this open. (Triage pass after the Cassandra 5.0 / JDK 17 modernization, #345.)

**Comment by jsevellec** [comment]
Closing as not reproducible on a supported version. This was reported against Cassandra 3.5 with the 3.x driver; the embedded server is now Cassandra 5.0.8 on JDK 17 with the 4.x driver, and there has been no report of this kind since. If it still happens on 5.x, please open a new issue with a thread dump (`jstack`) of the test JVM taken while it is stalled, plus the yaml in use.
