### ISSUE TITLE
Cassandra-unit doesn't specify a storage directory causing the daemon to not start

### ISSUE THREAD

**Issue by orium** [jsevellec/cassandra-unit#186]
```
[info] Exception encountered when attempting to run a suite with class name: org.scalatest.DeferredAbortedSuite *** ABORTED ***
[info]   java.lang.ExceptionInInitializerError:
[info]   at org.apache.cassandra.config.DatabaseDescriptor.<clinit>(DatabaseDescriptor.java:126)
[info]   at org.cassandraunit.utils.EmbeddedCassandraServerHelper.mkdirs(EmbeddedCassandraServerHelper.java:337)
[info]   at org.cassandraunit.utils.EmbeddedCassandraServerHelper.cleanupAndLeaveDirs(EmbeddedCassandraServerHelper.java:308)
[info]   at org.cassandraunit.utils.EmbeddedCassandraServerHelper.startEmbeddedCassandra(EmbeddedCassandraServerHelper.java:118)
[info]   at org.cassandraunit.utils.EmbeddedCassandraServerHelper.startEmbeddedCassandra(EmbeddedCassandraServerHelper.java:87)
[info]   at org.cassandraunit.utils.EmbeddedCassandraServerHelper.startEmbeddedCassandra(EmbeddedCassandraServerHelper.java:66)
[info]   at com.feedzai.cloud.common.CassandraTestUtils$.cassandraDatabase$lzycompute(CassandraTestUtils.scala:49)
[info]   at com.feedzai.cloud.common.CassandraTestUtils$.cassandraDatabase(CassandraTestUtils.scala:42)
[info]   at com.feedzai.cloud.udf.PersistentCounterSpec$CassandraPersistentCounter$.config(PersistentCounterSpec.scala:34)
[info]   at com.feedzai.cloud.udf.AbstractPersistentCounter.<init>(PersistentCounter.scala:215)
[info]   ...
[info]   Cause: org.apache.cassandra.exceptions.ConfigurationException: hints_directory is missing and -Dcassandra.storagedir is not set
[info]   at org.apache.cassandra.config.DatabaseDescriptor.applyConfig(DatabaseDescriptor.java:518)
[info]   at org.apache.cassandra.config.DatabaseDescriptor.<clinit>(DatabaseDescriptor.java:121)
[info]   at org.cassandraunit.utils.EmbeddedCassandraServerHelper.mkdirs(EmbeddedCassandraServerHelper.java:337)
[info]   at org.cassandraunit.utils.EmbeddedCassandraServerHelper.cleanupAndLeaveDirs(EmbeddedCassandraServerHelper.java:308)
[info]   at org.cassandraunit.utils.EmbeddedCassandraServerHelper.startEmbeddedCassandra(EmbeddedCassandraServerHelper.java:118)
[info]   at org.cassandraunit.utils.EmbeddedCassandraServerHelper.startEmbeddedCassandra(EmbeddedCassandraServerHelper.java:87)
[info]   at org.cassandraunit.utils.EmbeddedCassandraServerHelper.startEmbeddedCassandra(EmbeddedCassandraServerHelper.java:66)
[info]   at com.feedzai.cloud.common.CassandraTestUtils$.cassandraDatabase$lzycompute(CassandraTestUtils.scala:49)
[info]   at com.feedzai.cloud.common.CassandraTestUtils$.cassandraDatabase(CassandraTestUtils.scala:42)
[info]   at com.feedzai.cloud.udf.PersistentCounterSpec$CassandraPersistentCounter$.config(PersistentCounterSpec.scala:34)
```

**Comment by aliakhtar** [comment]
Same issue. I fixed it by doing `System.setProperty("cassandra.storagedir", "/tmp/cassandra" + System.nanoTime());` before creating CassandraCQLUnit
