### ISSUE TITLE
cleanEmbeddedCassandra throws "Cannot drop non existing keyspace"

### ISSUE THREAD

**Issue by amichair** [jsevellec/cassandra-unit#193]
I looks like the list of keyspaces it tries to delete is stale, so it attempts to delete a non-existing keyspace. Perhaps it can make sure the list isn't stale, or just use "DROP KEYSPACE IF EXISTS" to ignore this state.

> ...
> Caused by: com.datastax.driver.core.exceptions.InvalidConfigurationInQueryException: Cannot drop non existing keyspace 'TestKeyspace'.
>         at com.datastax.driver.core.exceptions.InvalidConfigurationInQueryException.copy(InvalidConfigurationInQueryException.java:37)
>         at com.datastax.driver.core.exceptions.InvalidConfigurationInQueryException.copy(InvalidConfigurationInQueryException.java:27)
>         at com.datastax.driver.core.DriverThrowables.propagateCause(DriverThrowables.java:37)
>         at com.datastax.driver.core.DefaultResultSetFuture.getUninterruptibly(DefaultResultSetFuture.java:245)
>         at com.datastax.driver.core.AbstractSession.execute(AbstractSession.java:68)
>         at com.datastax.driver.core.AbstractSession.execute(AbstractSession.java:43)
>         at org.cassandraunit.utils.EmbeddedCassandraServerHelper.dropKeyspacesWithNativeDriver(EmbeddedCassandraServerHelper.java:253)
>         at org.cassandraunit.utils.EmbeddedCassandraServerHelper.dropKeyspaces(EmbeddedCassandraServerHelper.java:207)
>         at org.cassandraunit.utils.EmbeddedCassandraServerHelper.cleanEmbeddedCassandra(EmbeddedCassandraServerHelper.java:164)
> ...

**Comment by arnabmitra** [comment]
I am getting the same issue on an ubuntu machine
Any thoughts?
`com.datastax.driver.core.exceptions.OperationTimedOutException: [localhost/127.0.0.1:9042] Timed out waiting for server response

	at com.datastax.driver.core.exceptions.OperationTimedOutException.copy(OperationTimedOutException.java:44)
	at com.datastax.driver.core.exceptions.OperationTimedOutException.copy(OperationTimedOutException.java:26)
	at com.datastax.driver.core.DriverThrowables.propagateCause(DriverThrowables.java:37)
	at com.datastax.driver.core.DefaultResultSetFuture.getUninterruptibly(DefaultResultSetFuture.java:245)
	at com.datastax.driver.core.AbstractSession.execute(AbstractSession.java:68)
	at com.datastax.driver.core.AbstractSession.execute(AbstractSession.java:43)
	at org.cassandraunit.utils.EmbeddedCassandraServerHelper.dropKeyspacesWithNativeDriver(EmbeddedCassandraServerHelper.java:253)
	at org.cassandraunit.utils.EmbeddedCassandraServerHelper.dropKeyspaces(EmbeddedCassandraServerHelper.java:207)`

**Comment by jxie418** [comment]
I got the same. any ideas

**Comment by jsevellec** [comment]
**Cause.** You were right about the cause: the keyspace list came from the driver's metadata snapshot, which was stale, so it tried to `DROP` a keyspace that no longer existed.

**Fixed in #345.** `cleanEmbeddedCassandra()` now reads the live list from `system_schema.keyspaces` rather than driver metadata (67a492d), so it can only drop what actually exists. Essentially the fix you suggested.

Fixed on `main` and shipping in **5.0.0**, which is not on Maven Central yet — Central still has 4.3.1.0. Docs: https://github.com/jsevellec/cassandra-unit/tree/main/docs

Closing as fixed; sorry this took so long.
