### ISSUE TITLE
ExceptionInInitializerError

### ISSUE THREAD

**Issue by geekbeast** [jsevellec/cassandra-unit#212]
There is some incompatibility causing problems when trying to start CassandraUnit on random port for 3.9 (https://github.com/kryptnostic/rhizome/tree/feature/try-cassandra-unit). This is an issue, because the main advantage of running Cassandra on a random port is low effort way of achieving test isolation versus spinning up something using docker or solving it within the test environment itself.

The test for compatibility is here: https://github.com/kryptnostic/rhizome/blob/feature/try-cassandra-unit/src/test/java/com/geekbeast/rhizome/tests/bootstrap/CassandraBootstrap.java

When I try the default configuration I get:
```
2017-01-12T14:37:47,539 INFO [main] com.geekbeast.rhizome.tests.bootstrap.CassandraBootstrap - Started cassandra on port: 9142
```
When I try the random port configuration I get the following strack-trace. 
```
java.lang.ExceptionInInitializerError
	at org.apache.cassandra.config.DatabaseDescriptor.<clinit>(DatabaseDescriptor.java:130)
	at org.cassandraunit.utils.EmbeddedCassandraServerHelper.mkdirs(EmbeddedCassandraServerHelper.java:400)
	at org.cassandraunit.utils.EmbeddedCassandraServerHelper.cleanupAndLeaveDirs(EmbeddedCassandraServerHelper.java:372)
	at org.cassandraunit.utils.EmbeddedCassandraServerHelper.startEmbeddedCassandra(EmbeddedCassandraServerHelper.java:126)
	at org.cassandraunit.utils.EmbeddedCassandraServerHelper.startEmbeddedCassandra(EmbeddedCassandraServerHelper.java:95)
	at org.cassandraunit.utils.EmbeddedCassandraServerHelper.startEmbeddedCassandra(EmbeddedCassandraServerHelper.java:74)
	at org.cassandraunit.utils.EmbeddedCassandraServerHelper.startEmbeddedCassandra(EmbeddedCassandraServerHelper.java:70)
	at com.geekbeast.rhizome.tests.bootstrap.CassandraBootstrap.startCassandra(CassandraBootstrap.java:19)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
Caused by: org.apache.cassandra.exceptions.ConfigurationException: cdc_raw_directory is missing and -Dcassandra.storagedir is not set
	at org.apache.cassandra.config.DatabaseDescriptor.applyConfig(DatabaseDescriptor.java:542)
	at org.apache.cassandra.config.DatabaseDescriptor.<clinit>(DatabaseDescriptor.java:125)
	... 22 more
```

**Comment by geekbeast** [comment]
After doing some debugging I was able to track down the cause.

The following block is getting hit, because `readAndAdaptYamlFile` is stripping 'cdc_raw_directory: target/embeddedCassandra/cdc' from the yaml file that is written out. 

```java
       if (conf.cdc_raw_directory == null)
        {
            conf.cdc_raw_directory = System.getProperty("cassandra.storagedir", null);
            if (conf.cdc_raw_directory == null)
                throw new ConfigurationException("cdc_raw_directory is missing and -Dcassandra.storagedir is not set", false);
            conf.cdc_raw_directory += File.separator + "cdc_raw";
        }
```
I need to go back and look readAndAdaptYaml since it mostly looks fine.

**Comment by geekbeast** [comment]
I was able to verify by setting a breakpoint after the YAML file is written and manually adding in the missing configuration item that cassandra startup successfully.

**Comment by geekbeast** [comment]
@jsevellec So the issue seems to be in the 3.1.1.0 release: https://github.com/jsevellec/cassandra-unit/blob/cassandra-unit-parent-3.1.1.0/cassandra-unit/src/main/resources/cu-cassandra-rndport.yaml 

I was able to work around it by using the latest one from master and adding it to my build. Since this seems to have already been fixed I will also close the issue. Hopefully, if anyone else runs into they'll save some time :)

**Comment by erikkemperman** [comment]
@jsevellec I am running into the same problem. If I understand things correctly, https://github.com/jsevellec/cassandra-unit/commit/c2599f86d33adc9af9f2bc99f6d6b4f1072117f8 would fix the situation? Would you consider doing a point-release with this fix in? Thanks in advance!
