### ISSUE TITLE
Embedded server startup error with Cassandra 3.10

### ISSUE THREAD

**Issue by amichair** [jsevellec/cassandra-unit#221]
When upgrading Cassandra from 3.9 to 3.10 (and cassandra-unit 3.1.3.2), the embedded server fails to start:
```
java.lang.NullPointerException: null
        at org.apache.cassandra.config.DatabaseDescriptor.createAllDirectories(DatabaseDescriptor.java:1152)
        at org.cassandraunit.utils.EmbeddedCassandraServerHelper.mkdirs(EmbeddedCassandraServerHelper.java:349)
        at org.cassandraunit.utils.EmbeddedCassandraServerHelper.cleanupAndLeaveDirs(EmbeddedCassandraServerHelper.java:321)
        at org.cassandraunit.utils.EmbeddedCassandraServerHelper.startEmbeddedCassandra(EmbeddedCassandraServerHelper.java:122)
        at org.cassandraunit.utils.EmbeddedCassandraServerHelper.startEmbeddedCassandra(EmbeddedCassandraServerHelper.java:91)
        at org.cassandraunit.utils.EmbeddedCassandraServerHelper.startEmbeddedCassandra(EmbeddedCassandraServerHelper.java:70)
        at org.cassandraunit.utils.EmbeddedCassandraServerHelper.startEmbeddedCassandra(EmbeddedCassandraServerHelper.java:62)
        at org.cassandraunit.utils.EmbeddedCassandraServerHelper.startEmbeddedCassandra(EmbeddedCassandraServerHelper.java:58)
...
```
The configuration seems to no longer be applied (it is null) - perhaps Cassandra changed something about its configuration initialization that broke this.

**Comment by BrainLogic** [comment]
Hi team.
This is improved in 3.1.4.0-SNAPSHOT. When 3.1.4.0 will be released?

**Comment by nevillelyh** [comment]
I found a workaround by calling `DatabaseDescriptor.daemonInitialization()` after creating the CassandraUnit instance.

**Comment by OrangeDog** [comment]
@nevillelyh what exactly did you do? There is no `CassandraUnit` class to make an instance of.
Before `startEmbeddedCassandra` it throws a `ConfigurationException`. After, and it's too late.

**Comment by OrangeDog** [comment]
Seems the fix is 95ce8b2e6

**Comment by userx91** [comment]
We are facing the same issue . It works if we use 3.1.4.0-SNAPSHOT . We cannot use a SNAPSHOT dependency on our production code .is this part of any ongoing milestone ? Can you please let us know when it will be released. 
@nevillelyh  @OrangeDog - The changes you mentioned are part of EmbeddedCassandraServerHelper.java in 3.1.4.0-SNAPSHOT right ? Which other version of Cassandra unit has this fix ?

**Comment by nevillelyh** [comment]
Sorry I ended up not using cassandra-unit since we ran into other problems that are not easily fixable.

**Comment by MrChrisPSimmons** [comment]
This seems to work around the problem.
```java
      try {
        EmbeddedCassandraServerHelper.startEmbeddedCassandra(timeout);
      }
      catch (NullPointerException e) {
        DatabaseDescriptor.daemonInitialization();
        EmbeddedCassandraServerHelper.startEmbeddedCassandra(timeout);
      }
```

**Comment by hsn10** [comment]
can you publish new JAR with this fix?

**Comment by OrangeDog** [comment]
As 3.3.0.1 broke other things (#247) can you please release 3.1.4.0.

**Comment by amichair** [comment]
This issue no longer occurs in release 3.3.0.2, so I'm closing it.
