### ISSUE TITLE
Getting Nullpointer in Files.provider during startup

### ISSUE THREAD

**Issue by svenakela** [jsevellec/cassandra-unit#224]
I've written a few tests that uses cassandra-unit, they are working in several workstations and also in a Bamboo server. But know these tests are executed in a Jenkins build agent (OpenJDK 8 Docker container) and it fails during startup of the Cassandra server.

I am currently on the latest release, 3.1.3.2.

Pre starting the Embedded Cassandra there's a short snippet of code that finds an available port to avoid port conflicts, creates a temp config file by reading in a template file and replaces the listening port with the available port number and starts the server with this config.

```Java
public class CassandraTestBase {

    private static int cassandraPort = 0;

    static {
        try {
            final File file = File.createTempFile("cassandra", ".yaml");
            file.deleteOnExit();
            final URI uri = ClassLoader.getSystemResource("cassandra.yml").toURI();
            final Path path = Paths.get(uri);
            String content = new String(Files.readAllBytes(path));
            cassandraPort = PortUtil.getNextAvailable();
            content = content.replaceAll("__PORT__", String.valueOf(cassandraPort));
            Files.write(Paths.get(file.getPath()), content.getBytes());

            EmbeddedCassandraServerHelper.startEmbeddedCassandra(file, System.getProperty("java.io.tmpdir"), 20000L);

        } catch (TTransportException | IOException | URISyntaxException | ConfigurationException e) {
            throw new RuntimeException(e.getMessage());
        }
    }

    /**
     * The port the cassandra node is listening on.
     *
     * @return int port number
     */
    public static int getCassandraPort() {
        return cassandraPort;
    }
 }
```

In the Jenkins build agent the test will fail on the line 
```Java
EmbeddedCassandraServerHelper.startEmbeddedCassandra(file, System.getProperty("java.io.tmpdir"), 20000L);
```

The stacktrace that follows:
```Java
java.lang.ExceptionInInitializerError
    at org.apache.cassandra.config.DatabaseDescriptor.<clinit>(DatabaseDescriptor.java:130)
    at org.cassandraunit.utils.EmbeddedCassandraServerHelper.mkdirs(EmbeddedCassandraServerHelper.java:400)
    at org.cassandraunit.utils.EmbeddedCassandraServerHelper.cleanupAndLeaveDirs(EmbeddedCassandraServerHelper.java:372)
    at org.cassandraunit.utils.EmbeddedCassandraServerHelper.startEmbeddedCassandra(EmbeddedCassandraServerHelper.java:126)
    at com.domain.testutils.CassandraTestBase.<clinit>(CassandraTestBase.java:36)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
  ...
  ...
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
    at java.nio.file.Files.provider(Files.java:97)
    at java.nio.file.Files.getFileStore(Files.java:1461)
    at org.apache.cassandra.config.DatabaseDescriptor.guessFileStore(DatabaseDescriptor.java:823)
    at org.apache.cassandra.config.DatabaseDescriptor.applyConfig(DatabaseDescriptor.java:553)
    at org.apache.cassandra.config.DatabaseDescriptor.<clinit>(DatabaseDescriptor.java:125)
```

Of course the Files.provider can't be null. Is this anyone else has experienced?

**Comment by svenakela** [comment]
I figured out what the problem was. The cassandra.yml file we use has relative paths like:

```
data_file_directories:
    - target/embeddedCassandra/data
```

This works when Maven (or Eclipse directly) is used for running the tests as the target directory will be there. But when Gradle is used to run the tests the `target` dir is never created. The `DatabaseDescriptor` will check if the lowest directory exists and if it doesn't it will traverse backwards until it finds something existing. When the `target` dir is missing it will throw a `Nullpointer`.

The solution is simple, check if there's a `build` or `target` and use correct directory.

**Comment by collinscangarella** [comment]
Is there an expected release date for this patch? We're still experiencing the problem in the most up to date version of the library, 3.1.3.2.

**Comment by M9k** [comment]
Same problem here with Windows, With default value it work fine.
I paste the complete error, so if someone search on Google for the same problem it will find this issue:
Exception (java.lang.NullPointerException) encountered during startup: null
java.lang.NullPointerException
        at java.nio.file.Files.provider(Files.java:97)
        at java.nio.file.Files.getFileStore(Files.java:1461)
        at org.apache.cassandra.config.DatabaseDescriptor.guessFileStore(DatabaseDescriptor.java:990)
        at org.apache.cassandra.config.DatabaseDescriptor.applySimpleConfig(DatabaseDescriptor.java:456)
        at org.apache.cassandra.config.DatabaseDescriptor.applyAll(DatabaseDescriptor.java:309)
        at org.apache.cassandra.config.DatabaseDescriptor.daemonInitialization(DatabaseDescriptor.java:141)
        at org.apache.cassandra.service.CassandraDaemon.applyConfig(CassandraDaemon.java:645)
        at org.apache.cassandra.service.CassandraDaemon.activate(CassandraDaemon.java:580)
        at org.apache.cassandra.service.CassandraDaemon.main(CassandraDaemon.java:689)
ERROR [main] 2017-08-31 01:29:06,588 CassandraDaemon.java:706 - Exception encountered during startup

**Comment by massenz** [comment]
Just FYI (and I only found it by coincidence) this appears to happen again if you run your tests with `./gradlew` and `JAVA_HOME` happens to point to Java 9.

My "alternative" is set to use Java 8 (so `java --version` would give `java version "1.8.0_161"`), but then `gradlew` prefers to use `JAVA_HOME` (which was incorrectly set) and encounters this error.

The fix is trivial: `unset JAVA_HOME`
(just leaving it here, in case others stumble onto it, now that people will start experimenting with Java 9, as it was totally puzzling)

**Comment by Rolice** [comment]
@massenz, thanks for the hint! Actually with me the `$JAVA_HOME` was not set and thus I was hitting this error. After setting it properly (under macOS) it fixed my issues. I have put this in my ~/.bashrc file:

```bash
export JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_192.jdk/Contents/Home/
```

**Comment by massenz** [comment]
@Rolice: actually, on MacOS, it's much better to use `libexec`, like this:

```
	java_home=$(/usr/libexec/java_home -v ${version}) 
```
More details [in this gist](https://gist.github.com/massenz/faff155523a50313be6f25a5b631a63d).

**Comment by vaibhav-46** [comment]
I am hitting a very similar issue as @svenakela. When running with gradle, initially the default 'target/embeddedCassandra' does not work because the folder target does not exist. One solution that I tried was to use a different path, but the relative paths in the config files lead to a NullPointerException. Is there a way to modify the yaml file to change all the "target/embeddedCassandra" to "build/embeddedCassandra" before starting Cassandra? If not, could someone mention any other work-arounds that might have worked for them?
