### ISSUE TITLE
no libsigar-amd64-linux.so in java.library.path

### ISSUE THREAD

**Issue by DavidRG13** [jsevellec/cassandra-unit#225]
Hello, 

I'm getting the following exceptions when running my tests:

Tried versions 3.0.0.1 and 3.1.3.2. 

Does anyone know how to workaround this issue? Am I doing something wrong?

```
org.hyperic.sigar.SigarException: no libsigar-amd64-linux.so in java.library.path
	at org.hyperic.sigar.Sigar.loadLibrary(Sigar.java:172)
	at org.hyperic.sigar.Sigar.<clinit>(Sigar.java:100)
	at org.apache.cassandra.utils.SigarLibrary.<init>(SigarLibrary.java:47)
	at org.apache.cassandra.utils.SigarLibrary.<clinit>(SigarLibrary.java:28)
	at org.apache.cassandra.service.StartupChecks$6.execute(StartupChecks.java:197)
	at org.apache.cassandra.service.StartupChecks.verify(StartupChecks.java:106)
	at org.apache.cassandra.service.CassandraDaemon.setup(CassandraDaemon.java:169)
	at org.apache.cassandra.service.CassandraDaemon.activate(CassandraDaemon.java:551)
	at org.cassandraunit.utils.EmbeddedCassandraServerHelper$1.run(EmbeddedCassandraServerHelper.java:125)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
java.lang.IllegalAccessError: tried to access method com.google.common.collect.Iterators.emptyIterator()Lcom/google/common/collect/UnmodifiableIterator; from class org.apache.cassandra.db.MutableDeletionInfo
Exception (java.lang.IllegalAccessError) encountered during startup: tried to access method com.google.common.collect.Iterators.emptyIterator()Lcom/google/common/collect/UnmodifiableIterator; from class org.apache.cassandra.db.MutableDeletionInfo
	at org.apache.cassandra.db.MutableDeletionInfo.rangeIterator(MutableDeletionInfo.java:159)
	at org.apache.cassandra.db.partitions.AbstractBTreePartition.sliceIterator(AbstractBTreePartition.java:199)
	at org.apache.cassandra.db.partitions.AbstractBTreePartition.unfilteredIterator(AbstractBTreePartition.java:190)
	at org.apache.cassandra.db.partitions.AbstractBTreePartition.unfilteredIterator(AbstractBTreePartition.java:177)
	at org.apache.cassandra.db.partitions.AbstractBTreePartition.unfilteredIterator(AbstractBTreePartition.java:172)
	at org.apache.cassandra.db.partitions.PartitionUpdate$PartitionUpdateSerializer.serializedSize(PartitionUpdate.java:710)
	at org.apache.cassandra.db.Mutation$MutationSerializer.serializedSize(Mutation.java:372)
	at org.apache.cassandra.db.commitlog.CommitLog.add(CommitLog.java:262)
	at org.apache.cassandra.db.Keyspace.apply(Keyspace.java:498)
	at org.apache.cassandra.db.Keyspace.apply(Keyspace.java:399)
	at org.apache.cassandra.db.Mutation.applyFuture(Mutation.java:202)
	at org.apache.cassandra.db.Mutation.apply(Mutation.java:214)
	at org.apache.cassandra.db.Mutation.apply(Mutation.java:228)
	at org.apache.cassandra.cql3.statements.ModificationStatement.executeInternalWithoutCondition(ModificationStatement.java:553)
	at org.apache.cassandra.cql3.statements.ModificationStatement.executeInternal(ModificationStatement.java:547)
	at org.apache.cassandra.cql3.QueryProcessor.executeInternal(QueryProcessor.java:295)
	at org.apache.cassandra.db.SystemKeyspace.removeTruncationRecord(SystemKeyspace.java:622)
	at org.apache.cassandra.db.ColumnFamilyStore.invalidate(ColumnFamilyStore.java:519)
	at org.apache.cassandra.db.ColumnFamilyStore.invalidate(ColumnFamilyStore.java:495)
	at org.apache.cassandra.schema.LegacySchemaMigrator.lambda$unloadLegacySchemaTables$278(LegacySchemaMigrator.java:136)
	at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:408)
	at org.apache.cassandra.schema.LegacySchemaMigrator.unloadLegacySchemaTables(LegacySchemaMigrator.java:136)
	at org.apache.cassandra.schema.LegacySchemaMigrator.migrate(LegacySchemaMigrator.java:82)
	at org.apache.cassandra.service.CassandraDaemon.setup(CassandraDaemon.java:223)
	at org.apache.cassandra.service.CassandraDaemon.activate(CassandraDaemon.java:551)
	at org.cassandraunit.utils.EmbeddedCassandraServerHelper$1.run(EmbeddedCassandraServerHelper.java:125)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
2017-03-09 10:14:37,652 ERROR [org.apache.cassandra.service.CassandraDaemon] - <Exception encountered during startup>
java.lang.IllegalAccessError: tried to access method com.google.common.collect.Iterators.emptyIterator()Lcom/google/common/collect/UnmodifiableIterator; from class org.apache.cassandra.db.MutableDeletionInfo
	at org.apache.cassandra.db.MutableDeletionInfo.rangeIterator(MutableDeletionInfo.java:159) ~[cassandra-all-3.4.jar:3.4]
	at org.apache.cassandra.db.partitions.AbstractBTreePartition.sliceIterator(AbstractBTreePartition.java:199) ~[cassandra-all-3.4.jar:3.4]
	at org.apache.cassandra.db.partitions.AbstractBTreePartition.unfilteredIterator(AbstractBTreePartition.java:190) ~[cassandra-all-3.4.jar:3.4]
	at org.apache.cassandra.db.partitions.AbstractBTreePartition.unfilteredIterator(AbstractBTreePartition.java:177) ~[cassandra-all-3.4.jar:3.4]
	at org.apache.cassandra.db.partitions.AbstractBTreePartition.unfilteredIterator(AbstractBTreePartition.java:172) ~[cassandra-all-3.4.jar:3.4]
	at org.apache.cassandra.db.partitions.PartitionUpdate$PartitionUpdateSerializer.serializedSize(PartitionUpdate.java:710) ~[cassandra-all-3.4.jar:3.4]
	at org.apache.cassandra.db.Mutation$MutationSerializer.serializedSize(Mutation.java:372) ~[cassandra-all-3.4.jar:3.4]
	at org.apache.cassandra.db.commitlog.CommitLog.add(CommitLog.java:262) ~[cassandra-all-3.4.jar:3.4]
	at org.apache.cassandra.db.Keyspace.apply(Keyspace.java:498) ~[cassandra-all-3.4.jar:3.4]
	at org.apache.cassandra.db.Keyspace.apply(Keyspace.java:399) ~[cassandra-all-3.4.jar:3.4]
	at org.apache.cassandra.db.Mutation.applyFuture(Mutation.java:202) ~[cassandra-all-3.4.jar:3.4]
	at org.apache.cassandra.db.Mutation.apply(Mutation.java:214) ~[cassandra-all-3.4.jar:3.4]
	at org.apache.cassandra.db.Mutation.apply(Mutation.java:228) ~[cassandra-all-3.4.jar:3.4]
	at org.apache.cassandra.cql3.statements.ModificationStatement.executeInternalWithoutCondition(ModificationStatement.java:553) ~[cassandra-all-3.4.jar:3.4]
	at org.apache.cassandra.cql3.statements.ModificationStatement.executeInternal(ModificationStatement.java:547) ~[cassandra-all-3.4.jar:3.4]
	at org.apache.cassandra.cql3.QueryProcessor.executeInternal(QueryProcessor.java:295) ~[cassandra-all-3.4.jar:3.4]
	at org.apache.cassandra.db.SystemKeyspace.removeTruncationRecord(SystemKeyspace.java:622) ~[cassandra-all-3.4.jar:3.4]
	at org.apache.cassandra.db.ColumnFamilyStore.invalidate(ColumnFamilyStore.java:519) ~[cassandra-all-3.4.jar:3.4]
	at org.apache.cassandra.db.ColumnFamilyStore.invalidate(ColumnFamilyStore.java:495) ~[cassandra-all-3.4.jar:3.4]
	at org.apache.cassandra.schema.LegacySchemaMigrator.lambda$unloadLegacySchemaTables$278(LegacySchemaMigrator.java:136) ~[cassandra-all-3.4.jar:3.4]
	at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:408) ~[guava-21.0.jar:?]
	at org.apache.cassandra.schema.LegacySchemaMigrator.unloadLegacySchemaTables(LegacySchemaMigrator.java:136) ~[cassandra-all-3.4.jar:3.4]
	at org.apache.cassandra.schema.LegacySchemaMigrator.migrate(LegacySchemaMigrator.java:82) ~[cassandra-all-3.4.jar:3.4]
	at org.apache.cassandra.service.CassandraDaemon.setup(CassandraDaemon.java:223) [cassandra-all-3.4.jar:3.4]
	at org.apache.cassandra.service.CassandraDaemon.activate(CassandraDaemon.java:551) [cassandra-all-3.4.jar:3.4]
	at org.cassandraunit.utils.EmbeddedCassandraServerHelper$1.run(EmbeddedCassandraServerHelper.java:125) [cassandra-unit-3.0.0.1.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_121]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
```

**Comment by DavidRG13** [comment]
Hello again:

I had a look into this and worked around this issue:

- In https://github.com/akka/apps/blob/master/akka-cluster-testapp/sigar/ you can find the needed .so files
- Add the libsigar library to java.libraty.path (you can see default values for each OS in http://stackoverflow.com/questions/20038789/default-java-library-path)

Is there another way of solving it?

**Comment by asarkar** [comment]
@DavidRG13 Why'd one introduce platform dependency in their build, isn't the whole point of Java to be platform-independent? What is this library for?

**Comment by Orange-apples** [comment]
use  docker , how to create the .so file in the container
