### ISSUE TITLE
java.lang.NoSuchMethodError: net.jpountz.lz4.LZ4Compressor.compress

### ISSUE THREAD

**Issue by pluckandr** [jsevellec/cassandra-unit#228]
We are using version 3.1.3.2 but encounter an error when initializing the cluster.
Versions 2.X work fine. Our application is running on Java 8.
We've tried to exclude lz4 dependency but it doesn't seem to work.
Exclusion:
`<dependency>
            <groupId>org.cassandraunit</groupId>
            <artifactId>cassandra-unit</artifactId>
            <version>${org.cassandraunit.version}</version>
            <scope>test</scope>
            <exclusions>
                <exclusion>
                    <groupId>net.jpountz.lz4</groupId>
                    <artifactId>lz4</artifactId>
                </exclusion>
            </exclusions>
        </dependency>`
Stacktrace:
`java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: net.jpountz.lz4.LZ4Compressor.compress(Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;)V
	at org.apache.cassandra.utils.FBUtilities.waitOnFuture(FBUtilities.java:403)
	at org.apache.cassandra.db.SystemKeyspace.forceBlockingFlush(SystemKeyspace.java:793)
	at org.apache.cassandra.db.SystemKeyspace.removeTruncationRecord(SystemKeyspace.java:639)
	at org.apache.cassandra.db.ColumnFamilyStore.invalidate(ColumnFamilyStore.java:541)
	at org.apache.cassandra.db.ColumnFamilyStore.invalidate(ColumnFamilyStore.java:517)
	at org.apache.cassandra.schema.LegacySchemaMigrator.lambda$unloadLegacySchemaTables$1(LegacySchemaMigrator.java:137)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at org.apache.cassandra.schema.LegacySchemaMigrator.unloadLegacySchemaTables(LegacySchemaMigrator.java:137)
	at org.apache.cassandra.schema.LegacySchemaMigrator.migrate(LegacySchemaMigrator.java:83)
	at org.apache.cassandra.service.CassandraDaemon.setup(CassandraDaemon.java:254)
	at org.apache.cassandra.service.CassandraDaemon.activate(CassandraDaemon.java:601)
	at org.cassandraunit.utils.EmbeddedCassandraServerHelper$1.run(EmbeddedCassandraServerHelper.java:129)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: net.jpountz.lz4.LZ4Compressor.compress(Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;)V
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at org.apache.cassandra.utils.FBUtilities.waitOnFuture(FBUtilities.java:399)
	... 14 more
Caused by: java.lang.NoSuchMethodError: net.jpountz.lz4.LZ4Compressor.compress(Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;)V
	at org.apache.cassandra.io.compress.LZ4Compressor.compress(LZ4Compressor.java:118)
	at org.apache.cassandra.io.compress.CompressedSequentialWriter.flushData(CompressedSequentialWriter.java:140)
	at org.apache.cassandra.io.util.SequentialWriter.doFlush(SequentialWriter.java:191)
	at org.apache.cassandra.io.util.SequentialWriter.syncInternal(SequentialWriter.java:184)
	at org.apache.cassandra.io.compress.CompressedSequentialWriter.access$100(CompressedSequentialWriter.java:38)
	at org.apache.cassandra.io.compress.CompressedSequentialWriter$TransactionalProxy.doPrepare(CompressedSequentialWriter.java:307)
	at org.apache.cassandra.utils.concurrent.Transactional$AbstractTransactional.prepareToCommit(Transactional.java:173)
	at org.apache.cassandra.io.util.SequentialWriter.prepareToCommit(SequentialWriter.java:358)
	at org.apache.cassandra.io.sstable.format.big.BigTableWriter$TransactionalProxy.doPrepare(BigTableWriter.java:351)
	at org.apache.cassandra.utils.concurrent.Transactional$AbstractTransactional.prepareToCommit(Transactional.java:173)
	at org.apache.cassandra.io.sstable.format.SSTableWriter.prepareToCommit(SSTableWriter.java:280)
	at org.apache.cassandra.io.sstable.SimpleSSTableMultiWriter.prepareToCommit(SimpleSSTableMultiWriter.java:101)
	at org.apache.cassandra.db.ColumnFamilyStore$Flush.flushMemtable(ColumnFamilyStore.java:1140)
	at org.apache.cassandra.db.ColumnFamilyStore$Flush.run(ColumnFamilyStore.java:1084)
	... 3 more`

**Comment by toxeh** [comment]
@pluckandr , set 1.3.0 version of lz4 in your pom.xml.
