### ISSUE TITLE
Cassandra-unit CLI

### ISSUE THREAD

**Issue by DavidRG13** [jsevellec/cassandra-unit#236]
Is there any reason to not continue with this alternative?
Is it possible to create another CLI release?

**Comment by DavidRG13** [comment]
Don't know if the current version allows it but I created a CLI release by hand , but it's not working...

Here the log:
```
Start Loading...
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/tmp/cassandra-unit/cassandra-unit-3.1.3.2/lib/logback-classic-1.1.3.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/tmp/cassandra-unit/cassandra-unit-3.1.3.2/lib/slf4j-log4j12-1.7.12.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [ch.qos.logback.classic.util.ContextSelectorStaticBinder]
13:46:59.724 [main] DEBUG c.d.driver.core.SystemProperties - com.datastax.driver.NEW_NODE_DELAY_SECONDS is undefined, using default value 1
13:46:59.734 [main] DEBUG c.d.driver.core.SystemProperties - com.datastax.driver.NOTIF_LOCK_TIMEOUT_SECONDS is undefined, using default value 60
13:46:59.756 [main] DEBUG c.d.driver.core.SystemProperties - com.datastax.driver.USE_NATIVE_CLOCK is undefined, using default value true
13:46:59.997 [main] INFO  c.datastax.driver.core.ClockFactory - Using native clock to generate timestamps.
13:47:00.009 [main] DEBUG c.d.driver.core.SystemProperties - com.datastax.driver.NON_BLOCKING_EXECUTOR_SIZE is undefined, using default value 12
13:47:00.073 [main] DEBUG com.datastax.driver.core.Cluster - Starting new cluster with contact points [localhost/127.0.0.1:9146]
13:47:00.094 [main] DEBUG i.n.u.i.l.InternalLoggerFactory - Using SLF4J as the default logging framework
13:47:00.117 [main] DEBUG i.n.util.internal.PlatformDependent0 - java.nio.Buffer.address: available
13:47:00.117 [main] DEBUG i.n.util.internal.PlatformDependent0 - sun.misc.Unsafe.theUnsafe: available
13:47:00.118 [main] DEBUG i.n.util.internal.PlatformDependent0 - sun.misc.Unsafe.copyMemory: available
13:47:00.118 [main] DEBUG i.n.util.internal.PlatformDependent0 - java.nio.Bits.unaligned: true
13:47:00.118 [main] DEBUG i.n.util.internal.PlatformDependent0 - java.nio.DirectByteBuffer.<init>(long, int): available
13:47:00.119 [main] DEBUG io.netty.util.internal.Cleaner0 - java.nio.ByteBuffer.cleaner(): available
13:47:00.120 [main] DEBUG i.n.util.internal.PlatformDependent - Java version: 8
13:47:00.120 [main] DEBUG i.n.util.internal.PlatformDependent - -Dio.netty.noUnsafe: false
13:47:00.120 [main] DEBUG i.n.util.internal.PlatformDependent - sun.misc.Unsafe: available
13:47:00.121 [main] DEBUG i.n.util.internal.PlatformDependent - -Dio.netty.noJavassist: false
13:47:00.121 [main] DEBUG i.n.util.internal.PlatformDependent - Javassist: unavailable
13:47:00.122 [main] DEBUG i.n.util.internal.PlatformDependent - You don't have Javassist in your class path or you don't have enough permission to load dynamically generated classes.  Please check the configuration for better performance.
13:47:00.122 [main] DEBUG i.n.util.internal.PlatformDependent - -Dio.netty.tmpdir: /tmp (java.io.tmpdir)
13:47:00.122 [main] DEBUG i.n.util.internal.PlatformDependent - -Dio.netty.bitMode: 64 (sun.arch.data.model)
13:47:00.122 [main] DEBUG i.n.util.internal.PlatformDependent - -Dio.netty.noPreferDirect: false
13:47:00.122 [main] DEBUG i.n.util.internal.PlatformDependent - io.netty.maxDirectMemory: 257425408 bytes
13:47:00.130 [main] DEBUG c.d.driver.core.SystemProperties - com.datastax.driver.FORCE_NIO is undefined, using default value false
13:47:00.131 [main] INFO  com.datastax.driver.core.NettyUtil - Did not find Netty's native epoll transport in the classpath, defaulting to NIO.
13:47:00.134 [main] DEBUG i.n.c.MultithreadEventLoopGroup - -Dio.netty.eventLoopThreads: 24
13:47:00.144 [main] DEBUG io.netty.channel.nio.NioEventLoop - -Dio.netty.noKeySetOptimization: false
13:47:00.144 [main] DEBUG io.netty.channel.nio.NioEventLoop - -Dio.netty.selectorAutoRebuildThreshold: 512
13:47:00.174 [main] DEBUG io.netty.util.ResourceLeakDetector - -Dio.netty.leakDetection.level: simple
13:47:00.174 [main] DEBUG io.netty.util.ResourceLeakDetector - -Dio.netty.leakDetection.maxRecords: 4
13:47:00.175 [main] DEBUG i.n.util.ResourceLeakDetectorFactory - Loaded default ResourceLeakDetector: io.netty.util.ResourceLeakDetector@7c729a55
13:47:00.180 [main] DEBUG c.d.driver.core.SystemProperties - com.datastax.driver.EXTENDED_PEER_CHECK is undefined, using default value true
13:47:00.277 [main] DEBUG com.datastax.driver.core.Host.STATES - [localhost/127.0.0.1:9146] preparing to open 1 new connections, total = 1
13:47:00.283 [main] DEBUG c.d.driver.core.SystemProperties - com.datastax.driver.DISABLE_COALESCING is undefined, using default value false
13:47:00.318 [main] DEBUG i.n.buffer.PooledByteBufAllocator - -Dio.netty.allocator.numHeapArenas: 2
13:47:00.318 [main] DEBUG i.n.buffer.PooledByteBufAllocator - -Dio.netty.allocator.numDirectArenas: 2
13:47:00.319 [main] DEBUG i.n.buffer.PooledByteBufAllocator - -Dio.netty.allocator.pageSize: 8192
13:47:00.319 [main] DEBUG i.n.buffer.PooledByteBufAllocator - -Dio.netty.allocator.maxOrder: 11
13:47:00.319 [main] DEBUG i.n.buffer.PooledByteBufAllocator - -Dio.netty.allocator.chunkSize: 16777216
13:47:00.319 [main] DEBUG i.n.buffer.PooledByteBufAllocator - -Dio.netty.allocator.tinyCacheSize: 512
13:47:00.319 [main] DEBUG i.n.buffer.PooledByteBufAllocator - -Dio.netty.allocator.smallCacheSize: 256
13:47:00.319 [main] DEBUG i.n.buffer.PooledByteBufAllocator - -Dio.netty.allocator.normalCacheSize: 64
13:47:00.319 [main] DEBUG i.n.buffer.PooledByteBufAllocator - -Dio.netty.allocator.maxCachedBufferCapacity: 32768
13:47:00.319 [main] DEBUG i.n.buffer.PooledByteBufAllocator - -Dio.netty.allocator.cacheTrimInterval: 8192
13:47:00.345 [main] DEBUG i.n.util.internal.ThreadLocalRandom - -Dio.netty.initialSeedUniquifier: 0x5b34c456c4ea047f (took 0 ms)
13:47:00.370 [main] DEBUG io.netty.buffer.ByteBufUtil - -Dio.netty.allocator.type: unpooled
13:47:00.371 [main] DEBUG io.netty.buffer.ByteBufUtil - -Dio.netty.threadLocalDirectBufferSize: 65536
13:47:00.371 [main] DEBUG io.netty.buffer.ByteBufUtil - -Dio.netty.maxThreadLocalCharBufferSize: 16384
13:47:00.465 [cluster1-nio-worker-0] DEBUG com.datastax.driver.core.Connection - Connection[localhost/127.0.0.1:9146-1, inFlight=0, closed=false] Error connecting to localhost/127.0.0.1:9146 (Connection refused: localhost/127.0.0.1:9146)
13:47:00.466 [cluster1-nio-worker-0] DEBUG com.datastax.driver.core.Host.STATES - Defuncting Connection[localhost/127.0.0.1:9146-1, inFlight=0, closed=false] because: [localhost/127.0.0.1:9146] Cannot connect
13:47:00.467 [cluster1-nio-worker-0] DEBUG com.datastax.driver.core.Host.STATES - [localhost/127.0.0.1:9146] preventing new connections for the next 1000 ms
13:47:00.467 [cluster1-nio-worker-0] DEBUG com.datastax.driver.core.Host.STATES - [localhost/127.0.0.1:9146] Connection[localhost/127.0.0.1:9146-1, inFlight=0, closed=false] failed, remaining = 0
13:47:00.468 [cluster1-nio-worker-0] DEBUG com.datastax.driver.core.Connection - Connection[localhost/127.0.0.1:9146-1, inFlight=0, closed=true] closing connection
13:47:00.476 [main] DEBUG c.d.driver.core.ControlConnection - [Control connection] error on localhost/127.0.0.1:9146 connection, no more host to try
com.datastax.driver.core.exceptions.TransportException: [localhost/127.0.0.1:9146] Cannot connect
	at com.datastax.driver.core.Connection$1.operationComplete(Connection.java:166) ~[cassandra-driver-core-3.1.4.jar:na]
	at com.datastax.driver.core.Connection$1.operationComplete(Connection.java:149) ~[cassandra-driver-core-3.1.4.jar:na]
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:514) ~[netty-common-4.0.39.Final.jar:4.0.39.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:507) ~[netty-common-4.0.39.Final.jar:4.0.39.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:486) ~[netty-common-4.0.39.Final.jar:4.0.39.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:427) ~[netty-common-4.0.39.Final.jar:4.0.39.Final]
	at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:129) ~[netty-common-4.0.39.Final.jar:4.0.39.Final]
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.fulfillConnectPromise(AbstractNioChannel.java:272) ~[netty-transport-4.0.39.Final.jar:4.0.39.Final]
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:288) ~[netty-transport-4.0.39.Final.jar:4.0.39.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:589) ~[netty-transport-4.0.39.Final.jar:4.0.39.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:513) ~[netty-transport-4.0.39.Final.jar:4.0.39.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:427) ~[netty-transport-4.0.39.Final.jar:4.0.39.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:399) ~[netty-transport-4.0.39.Final.jar:4.0.39.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:140) ~[netty-common-4.0.39.Final.jar:4.0.39.Final]
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144) ~[netty-common-4.0.39.Final.jar:4.0.39.Final]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_131]
Caused by: java.net.ConnectException: Connection refused: localhost/127.0.0.1:9146
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[na:1.8.0_131]
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717) ~[na:1.8.0_131]
	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:223) ~[netty-transport-4.0.39.Final.jar:4.0.39.Final]
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:285) ~[netty-transport-4.0.39.Final.jar:4.0.39.Final]
	... 7 common frames omitted
13:47:00.477 [main] DEBUG com.datastax.driver.core.Cluster - Shutting down
Exception in thread "main" com.datastax.driver.core.exceptions.NoHostAvailableException: All host(s) tried for query failed (tried: localhost/127.0.0.1:9146 (com.datastax.driver.core.exceptions.TransportException: [localhost/127.0.0.1:9146] Cannot connect))
	at com.datastax.driver.core.ControlConnection.reconnectInternal(ControlConnection.java:233)
	at com.datastax.driver.core.ControlConnection.connect(ControlConnection.java:79)
	at com.datastax.driver.core.Cluster$Manager.init(Cluster.java:1483)
	at com.datastax.driver.core.Cluster.init(Cluster.java:159)
	at com.datastax.driver.core.Cluster.connectAsync(Cluster.java:330)
	at com.datastax.driver.core.Cluster.connectAsync(Cluster.java:305)
	at com.datastax.driver.core.Cluster.connect(Cluster.java:247)
	at org.cassandraunit.cli.CassandraUnitCommandLineLoader.otherTypeOfDataSetLoad(CassandraUnitCommandLineLoader.java:84)
	at org.cassandraunit.cli.CassandraUnitCommandLineLoader.load(CassandraUnitCommandLineLoader.java:71)
	at org.cassandraunit.cli.CassandraUnitCommandLineLoader.main(CassandraUnitCommandLineLoader.java:30)

```

**Comment by DavidRG13** [comment]
Ok, after all the investigations and work done I managed to make this work. Now a Cassandra instance can be started and dataset could be passed to it.

I guess the GitHub downloads feature is not longer available, isn't it? Where can I download the .tar that assemble-plugin creates?

FYI, I 'm working on a fork and will do a PR when ready 

Really useful lib ;)

**Comment by DavidRG13** [comment]
Could the tar.gz file be added to the release page? 
https://github.com/jsevellec/cassandra-unit/releases/tag/cassandra-unit-parent-3.1.3.2

**Comment by DavidRG13** [comment]
OK... my fault... 
Just realized that it's deployed to maven central. 
Closing this issue
