### ISSUE TITLE
failure to initialize embedded cassandra on Ubuntu

### ISSUE THREAD

**Issue by aashishs101** [jsevellec/cassandra-unit#244]
Running the following:

`EmbeddedCassandraServerHelper.startEmbeddedCassandra(100000)
val cluster = new Cluster.Builder().addContactPoints("127.0.0.1").withPort(9142).build()
val session = cluster.connect()
`

> java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
  at shade.com.datastax.spark.connector.google.common.base.Throwables.propagate(Throwables.java:160)
  at com.datastax.driver.core.NettyUtil.newEventLoopGroupInstance(NettyUtil.java:136)
  at com.datastax.driver.core.NettyOptions.eventLoopGroup(NettyOptions.java:99)
  at com.datastax.driver.core.Connection$Factory.<init>(Connection.java:769)
  at com.datastax.driver.core.Cluster$Manager.init(Cluster.java:1410)
  at com.datastax.driver.core.Cluster.init(Cluster.java:159)
  at com.datastax.driver.core.Cluster.connectAsync(Cluster.java:330)
  at com.datastax.driver.core.Cluster.connectAsync(Cluster.java:305)
  at com.datastax.driver.core.Cluster.connect(Cluster.java:247)
  at org.cassandraunit.utils.EmbeddedCassandraServerHelper.startEmbeddedCassandra(EmbeddedCassandraServerHelper.java:149)
  at org.cassandraunit.utils.EmbeddedCassandraServerHelper.startEmbeddedCassandra(EmbeddedCassandraServerHelper.java:91)
  at org.cassandraunit.utils.EmbeddedCassandraServerHelper.startEmbeddedCassandra(EmbeddedCassandraServerHelper.java:70)
  at org.cassandraunit.utils.EmbeddedCassandraServerHelper.startEmbeddedCassandra(EmbeddedCassandraServerHelper.java:62)
  ... 43 elided
Caused by: java.lang.reflect.InvocationTargetException: java.lang.VerifyError: class io.netty.channel.epoll.EpollEventLoop overrides final method pendingTasks.()I
  at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
  at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
  at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
  at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
  at com.datastax.driver.core.NettyUtil.newEventLoopGroupInstance(NettyUtil.java:134)
  ... 54 more
Caused by: java.lang.VerifyError: class io.netty.channel.epoll.EpollEventLoop overrides final method pendingTasks.()I
  at java.lang.ClassLoader.defineClass1(Native Method)
  at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
  at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
  at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
  at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
  at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
  at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
  at java.security.AccessController.doPrivileged(Native Method)
  at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
  at io.netty.channel.epoll.EpollEventLoopGroup.newChild(EpollEventLoopGroup.java:114)
  at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:64)
  at io.netty.channel.MultithreadEventLoopGroup.<init>(MultithreadEventLoopGroup.java:49)
  at io.netty.channel.epoll.EpollEventLoopGroup.<init>(EpollEventLoopGroup.java:93)
  at io.netty.channel.epoll.EpollEventLoopGroup.<init>(EpollEventLoopGroup.java:80)
  at io.netty.channel.epoll.EpollEventLoopGroup.<init>(EpollEventLoopGroup.java:61)
  ... 59 more

This snippet works both on different environments (a mac and Windows machine), but is failing in an Ubuntu environment.  This issue occurs on version 3.1.3.2 with Scala 2.11.

**Comment by aroch** [comment]
I'm seeing this issue on Fedora, same versions as above. Did anyone find a solution to this?

**Comment by atamborrino** [comment]
Same issue here. I think this has to do with cassandra-spark-connector package, because without it cassandra-unit runs well on Ubuntu.

**Comment by fchovich** [comment]
updates?

**Comment by aroch** [comment]
Don't know if it helps, but we realized a better approach for us would be to test again a real Cassandra on a docker container.

**Comment by fchovich** [comment]
I was able to solve excluding netty packages from cassandra-driver.

**Comment by jsevellec** [comment]
**I could not reproduce this, so treat what follows as a likely fix rather than a verified one.**

Several startup failure modes have been fixed since: the storage directories now honour `tmpDir` (they previously kept hardcoded `target/embeddedCassandra/*` paths regardless), `cleanup()` no longer throws when a directory is absent, and the whole thing runs on Cassandra 5.0.8 / JDK 17 rather than a Java-8-only server.

Closing on that basis to get the tracker honest, but please **reopen** if it still happens against 5.0.0 — a reopened issue with a stack trace is much more useful than this one sitting open and unanswered for years. 5.0.0 is on `main` but not yet on Maven Central.

Sorry for the long silence.
