### ISSUE TITLE
Issues when using different logging framework to Logback

### ISSUE THREAD

**Issue by JunayedMizan** [jsevellec/cassandra-unit#267]
When we introduced `cassandra-unit` to write integration tests we get the following error message:
```
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/home/bob/.m2/repository/org/apache/logging/log4j/log4j-slf4j-impl/2.10.0/log4j-slf4j-impl-2.10.0.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/home/bob/.m2/repository/ch/qos/logback/logback-classic/1.2.3/logback-classic-1.2.3.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.apache.logging.slf4j.Log4jLoggerFactory]
2018-04-26T13:01:14,186 WARN  main  org.apache.cassandra.config.DatabaseDescriptor - index_interval has been deprecated and should be removed from cassandra.yaml
2018-04-26T13:01:14,192 WARN  main  org.apache.cassandra.config.DatabaseDescriptor - Please rename encryption_options as server_encryption_options in the yaml
java.lang.ClassCastException: org.apache.logging.slf4j.Log4jLogger cannot be cast to ch.qos.logback.classic.Logger
	at org.apache.cassandra.cql3.functions.ThreadAwareSecurityManager.install(ThreadAwareSecurityManager.java:92)
	at org.apache.cassandra.service.CassandraDaemon.setup(CassandraDaemon.java:192)
	at org.apache.cassandra.service.CassandraDaemon.activate(CassandraDaemon.java:600)
	at org.cassandraunit.utils.EmbeddedCassandraServerHelper.lambda$startEmbeddedCassandra$1(EmbeddedCassandraServerHelper.java:144)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

We use a different logging framework to that used in `cassandra-unit` (i.e. Logback) and don't want to migrate to Logback.

I've had a look at the `github` repository for `cassandra-unit` and have noticed that in `org.apache.cassandra.cql3.functions.ThreadAwareSecurityManager`, Logback is hard codded e.g.
`ch.qos.logback.classic.Logger logbackLogger = (ch.qos.logback.classic.Logger) l;`

Is there a reason for hard coding Logback? Will this be resolved in future releases? Is there a workaround for using alternative logging framework where the above error will not be thrown.

We are using `cassandra-unit-spring` version `3.3.0.2` for our integration tests

**Comment by yarix** [comment]
I'm facing the same problem with the hard-coded logbacklogger.
 I'm using `cassandra-unit-3.5.0.1` and my project also use slf4j-log4j
```
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/C:/Users/amary/.m2/repository/ch/qos/logback/logback-classic/1.1.3/logback-classic-1.1.3.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/C:/Users/amary/.m2/repository/org/slf4j/slf4j-log4j12/1.7.2/slf4j-log4j12-1.7.2.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [ch.qos.logback.classic.util.ContextSelectorStaticBinder]
20:22:02.534 [main] DEBUG o.c.u.EmbeddedCassandraServerHelper - Starting cassandra...
```
To avoid the multiple binding, I exclude the `logback-classic` from cassandra unit, which resulted in the following error (again due to hard coded class name in `ThreadAwareSecurityManager`
```
28 Jun 2018 20:27:42,877	INFO 	[org.apache.cassandra.net.RateBasedBackPressure]	Initialized back-pressure with high ratio: 0.9, factor: 5, flow: FAST, window size: 15000.
28 Jun 2018 20:27:42,877	INFO 	[org.apache.cassandra.config.DatabaseDescriptor]	Back-pressure is disabled with strategy null.
28 Jun 2018 20:27:43,315	INFO 	[org.apache.cassandra.db.commitlog.CommitLog]	No commitlog files found; skipping replay

java.lang.NoClassDefFoundError: ch/qos/logback/classic/Logger
	at org.apache.cassandra.cql3.functions.ThreadAwareSecurityManager.install(ThreadAwareSecurityManager.java:92)
	at org.apache.cassandra.service.CassandraDaemon.setup(CassandraDaemon.java:192)
	at org.apache.cassandra.service.CassandraDaemon.activate(CassandraDaemon.java:602)
	at org.cassandraunit.utils.EmbeddedCassandraServerHelper.lambda$startEmbeddedCassandra$1(EmbeddedCassandraServerHelper.java:150)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: ch.qos.logback.classic.Logger
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 7 more

```

**Comment by oliverlockwood** [comment]
@jsevellec would you be willing to consider a PR which removes the hard dependency on Logback?

**Comment by EduardZaft** [comment]
Is here any work on removing the hard coded dependency on logback?

**Comment by jsevellec** [comment]
The issue should be fixed. The hardcoded dependency  was not on the cassandra-unit side but was coming from the Cassandra dependendy. They fixed it and now. I've updated the cassandra-unit pom.xml to use the newer cassandra version
