### ISSUE TITLE
Sigar Exception - 

### ISSUE THREAD

**Issue by nilaybose** [jsevellec/cassandra-unit#284]
How can this be fixed without any work around 
org.hyperic.sigar.SigarException: no libsigar-universal64-macosx.dylib in java.library.path

	at org.hyperic.sigar.Sigar.loadLibrary(Sigar.java:172)

	at org.hyperic.sigar.Sigar.<clinit>(Sigar.java:100)

	at org.apache.cassandra.utils.SigarLibrary.<init>(SigarLibrary.java:47)

	at org.apache.cassandra.utils.SigarLibrary.<clinit>(SigarLibrary.java:28)

	at org.apache.cassandra.service.StartupChecks$7.execute(StartupChecks.java:266)

	at org.apache.cassandra.service.StartupChecks.verify(StartupChecks.java:125)

	at org.apache.cassandra.service.CassandraDaemon.setup(CassandraDaemon.java:200)

	at org.apache.cassandra.service.CassandraDaemon.activate(CassandraDaemon.java:602)

	at org.cassandraunit.utils.EmbeddedCassandraServerHelper.lambda$startEmbeddedCassandra$1(EmbeddedCassandraServerHelper.java:150)

	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)

	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)

	at java.lang.Thread.run(Thread.java:748)

**Comment by nilaybose** [comment]
It seems that if we use log4j 1.2 as dependency

testCompile group: 'log4j', name: 'log4j', version: '1.2.17'  

**This error will not be logged by Sigar Library ( as native logging is turned off by default )**

We can turn on this logging for the native ( *.so)  by using the system property

System.setProperty("sigar.nativeLogging", "true") ;
