### ISSUE TITLE
Errors on startup

### ISSUE THREAD

**Issue by brianmhess** [jsevellec/cassandra-unit#301]
I am using CassandraUnit with a small Java app.  I get the following errors on startup:

```
ERROR cassandra.jmx.local.port missing from cassandra-env.sh, unable to start local JMX service.
no libsigar-amd64-linux.so in java.library.path
org.hyperic.sigar.SigarException: no libsigar-amd64-linux.so in java.library.path
  at org.hyperic.sigar.Sigar.loadLibrary(Sigar.java:172)
  at org.hyperic.sigar.Sigar.<clinit>(Sigar.java:100)
  at org.apache.cassandra.utils.SigarLibrary.<init>(SigarLibrary.java:47)
  at org.apache.cassandra.utils.SigarLibrary.<clinit>(SigarLibrary.java:28)
  at org.apache.cassandra.service.StartupChecks$7.execute(StartupChecks.java:266)
  at org.apache.cassandra.service.StartupChecks.verify(StartupChecks.java:125)
  at org.apache.cassandra.service.CassandraDaemon.setup(CassandraDaemon.java:200)
  at org.apache.cassandra.service.CassandraDaemon.activate(CassandraDaemon.java:620)
  at org.cassandraunit.utils.EmbeddedCassandraServerHelper.lambda$startEmbeddedCassandra$1(EmbeddedCassandraServerHelper.java:152)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
  at java.lang.Thread.run(Thread.java:748)
```

I am using version 3.7.1.0.  It seems to be similar to issue 225, but I couldn't get the work around to work.

**Comment by jsevellec** [comment]
**I could not reproduce this, so treat what follows as a likely fix rather than a verified one.**

Startup errors from this era were usually the Java 8 pin or the storage directories. Both changed: Cassandra 5.0.8 on JDK 17, and `tmpDir` now genuinely relocates data, commitlog, hints, saved caches and CDC. A startup failure also surfaces properly now rather than killing the JVM — the daemon is created managed, so Cassandra's `System.exit` path is not taken.

Closing on that basis to get the tracker honest, but please **reopen** if it still happens against 5.0.0 — a reopened issue with a stack trace is much more useful than this one sitting open and unanswered for years. 5.0.0 is on `main` but not yet on Maven Central.

Sorry for the long silence.
