### ISSUE TITLE
Unable to check disk space available to target/embeddedCassandra/commitlog

### ISSUE THREAD

**Issue by KovaxG** [jsevellec/cassandra-unit#316]
Hello, I am trying to run a project on my local computer, but I get the following when trying to run unit tests.

```
org.apache.cassandra.exceptions.ConfigurationException: Unable to check disk space available to target/embeddedCassandra/commitlog. Perhaps the Cassandra user does not have the necessary permissions
	at org.apache.cassandra.config.DatabaseDescriptor.applySimpleConfig(DatabaseDescriptor.java:498)
        ...

Caused by: java.io.IOException: Mount point not found
	at sun.nio.fs.LinuxFileStore.findMountEntry(LinuxFileStore.java:100)
	at sun.nio.fs.UnixFileStore.<init>(UnixFileStore.java:65)
	at sun.nio.fs.LinuxFileStore.<init>(LinuxFileStore.java:44)
	at sun.nio.fs.LinuxFileSystemProvider.getFileStore(LinuxFileSystemProvider.java:51)
	at sun.nio.fs.LinuxFileSystemProvider.getFileStore(LinuxFileSystemProvider.java:39)
	at sun.nio.fs.UnixFileSystemProvider.getFileStore(UnixFileSystemProvider.java:368)
	at java.nio.file.Files.getFileStore(Files.java:1461)
	at org.apache.cassandra.io.util.FileUtils.getFileStore(FileUtils.java:682)
	at org.apache.cassandra.config.DatabaseDescriptor.guessFileStore(DatabaseDescriptor.java:1067)
```
Some other information:

```
$ java -version
openjdk version "1.8.0_265"
OpenJDK Runtime Environment (build 1.8.0_265-b01)
OpenJDK 64-Bit Server VM (build 25.265-b01, mixed mode)
```

I have been trying to get to the bottom of this for a day, but to no success. I use Manjaro Linux, and I have no idea why cassandra has issues acessing the `target/embeddedCassandra` folder. I also couldn't really find this issue online.
I would appreciate any help, thank you.

**Comment by Dionakov** [comment]
Hello,
I don't know if you're still encountering this issue but it might help someone else.
I had the same issue running Manjaro. I did a full system upgrade and installed kernel linux511 and it solved the issue.

**Comment by iopanda** [comment]
I have the same issue when my testing running in Jenkins job which in container.


```
09:11:09      org.apache.cassandra.exceptions.ConfigurationException: Unable to check disk space available to target/cassandra_embedded/cdc_raw. Perhaps the Cassandra user does not have the necessary permissions
09:11:09      	at org.apache.cassandra.config.DatabaseDescriptor.applySimpleConfig(DatabaseDescriptor.java:525)
09:11:09      	at org.apache.cassandra.config.DatabaseDescriptor.applyAll(DatabaseDescriptor.java:324)
09:11:09      	at org.apache.cassandra.config.DatabaseDescriptor.daemonInitialization(DatabaseDescriptor.java:153)
09:11:09      	at org.apache.cassandra.config.DatabaseDescriptor.daemonInitialization(DatabaseDescriptor.java:137)
09:11:09      	at org.apache.cassandra.service.CassandraDaemon.applyConfig(CassandraDaemon.java:680)
09:11:09      	at org.apache.cassandra.service.CassandraDaemon.activate(CassandraDaemon.java:622)
09:11:09      	at info.archinnov.achilles.embedded.ServerStarter.lambda$start$0(ServerStarter.java:163)
09:11:09      	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
09:11:09      	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
09:11:09      	at java.base/java.lang.Thread.run(Thread.java:834)
09:11:09      Caused by: java.io.IOException: Mount point not found
09:11:09      	at java.base/sun.nio.fs.LinuxFileStore.findMountEntry(LinuxFileStore.java:105)
09:11:09      	at java.base/sun.nio.fs.UnixFileStore.<init>(UnixFileStore.java:67)
09:11:09      	at java.base/sun.nio.fs.LinuxFileStore.<init>(LinuxFileStore.java:49)
09:11:09      	at java.base/sun.nio.fs.LinuxFileSystemProvider.getFileStore(LinuxFileSystemProvider.java:51)
09:11:09      	at java.base/sun.nio.fs.LinuxFileSystemProvider.getFileStore(LinuxFileSystemProvider.java:39)
09:11:09      	at java.base/sun.nio.fs.UnixFileSystemProvider.getFileStore(UnixFileSystemProvider.java:369)
09:11:09      	at java.base/java.nio.file.Files.getFileStore(Files.java:1487)
09:11:09      	at org.apache.cassandra.io.util.FileUtils.getFileStore(FileUtils.java:682)
09:11:09      	at org.apache.cassandra.config.DatabaseDescriptor.guessFileStore(DatabaseDescriptor.java:1087)
09:11:09      	at org.apache.cassandra.config.DatabaseDescriptor.applySimpleConfig(DatabaseDescriptor.java:520)
09:11:09      	... 9 more
09:11:10  
```

Anyone can help on this?

**Comment by jsevellec** [comment]
**Cause.** Cassandra checked disk space against `target/embeddedCassandra/commitlog`, and `cleanup()` threw outright if a configured directory was absent.

**Fixed in #345.** `tmpDir` now actually relocates every storage directory, the default resolves against `java.io.tmpdir` instead of assuming Maven's `target/`, and `cleanup()` treats a missing directory as already-clean rather than throwing (f148112).

Fixed on `main` and shipping in **5.0.0**, which is not on Maven Central yet — Central still has 4.3.1.0. Docs: https://github.com/jsevellec/cassandra-unit/tree/main/docs

Closing as fixed; sorry this took so long.
