### ISSUE TITLE
[2021-06-14T14:58:06.055Z] org.apache.cassandra.exceptions.ConfigurationException: Unable to check disk space available to target/embeddedCassandra/commitlog. Perhaps the Cassandra user does not have the necessary permissions

### ISSUE THREAD

**Issue by claudioabudio** [jsevellec/cassandra-unit#327]
This happens on a jenkins build, which i believe runs on linux, I don't believe it happens on windows where we run our local builds:
Also note this does not happen always, sometimes it does , sometimes it does not, so could it be a sort of race condition ? 

Full exception below: 

``
[2021-06-14T14:58:06.055Z] 2021-06-14 14:58:05.790 [main] ERROR c.j.c.m.h.f.f.b.c.EmbeddedCassandraSetup - Can't start Embedded Cassandra
[2021-06-14T14:58:06.055Z] org.apache.cassandra.exceptions.ConfigurationException: Unable to check disk space available to target/embeddedCassandra/commitlog. Perhaps the Cassandra user does not have the necessary permissions
[2021-06-14T14:58:06.055Z] 	at org.apache.cassandra.config.DatabaseDescriptor.applySimpleConfig(DatabaseDescriptor.java:498)
[2021-06-14T14:58:06.055Z] 	at org.apache.cassandra.config.DatabaseDescriptor.applyAll(DatabaseDescriptor.java:324)
[2021-06-14T14:58:06.055Z] 	at org.apache.cassandra.config.DatabaseDescriptor.daemonInitialization(DatabaseDescriptor.java:153)
[2021-06-14T14:58:06.055Z] 	at org.apache.cassandra.config.DatabaseDescriptor.daemonInitialization(DatabaseDescriptor.java:137)
[2021-06-14T14:58:06.055Z] 	at org.cassandraunit.utils.EmbeddedCassandraServerHelper.startEmbeddedCassandra(EmbeddedCassandraServerHelper.java:145)
[2021-06-14T14:58:06.055Z] 	at org.cassandraunit.utils.EmbeddedCassandraServerHelper.startEmbeddedCassandra(EmbeddedCassandraServerHelper.java:108)
[2021-06-14T14:58:06.055Z] 	at org.cassandraunit.utils.EmbeddedCassandraServerHelper.startEmbeddedCassandra(EmbeddedCassandraServerHelper.java:88)
[2021-06-14T14:58:06.055Z] 	at org.cassandraunit.utils.EmbeddedCassandraServerHelper.startEmbeddedCassandra(EmbeddedCassandraServerHelper.java:80)
[2021-06-14T14:58:06.055Z] 	at com.jpmorgan.cib.mst.helix.fund.funding.bdd.config.EmbeddedCassandraSetup.init(EmbeddedCassandraSetup.java:23)
[2021-06-14T14:58:06.055Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2021-06-14T14:58:06.055Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2021-06-14T14:58:06.055Z] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2021-06-14T14:58:06.055Z] 	at java.lang.reflect.Method.invoke(Method.java:498)
[2021-06-14T14:58:06.055Z] 	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:389)
[2021-06-14T14:58:06.055Z] 	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:333)
[2021-06-14T14:58:06.055Z] 	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:157)
[2021-06-14T14:58:06.055Z] 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:415)
[2021-06-14T14:58:06.055Z] 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1791)
[2021-06-14T14:58:06.055Z] 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:594)
[2021-06-14T14:58:06.055Z] 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:516)
[2021-06-14T14:58:06.055Z] 	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:324)
[2021-06-14T14:58:06.055Z] 	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
[2021-06-14T14:58:06.055Z] 	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:322)
[2021-06-14T14:58:06.055Z] 	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
[2021-06-14T14:58:06.055Z] 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:897)
[2021-06-14T14:58:06.055Z] 	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:879)
[2021-06-14T14:58:06.056Z] 	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:551)
[2021-06-14T14:58:06.056Z] 	at org.springframework.boot.web.reactive.context.ReactiveWebServerApplicationContext.refresh(ReactiveWebServerApplicationContext.java:62)
[2021-06-14T14:58:06.056Z] 	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:755)
[2021-06-14T14:58:06.056Z] 	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:747)
[2021-06-14T14:58:06.056Z] 	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:402)
[2021-06-14T14:58:06.056Z] 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:312)
[2021-06-14T14:58:06.056Z] 	at org.springframework.boot.test.context.SpringBootContextLoader.loadContext(SpringBootContextLoader.java:120)
[2021-06-14T14:58:06.056Z] 	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContextInternal(DefaultCacheAwareContextLoaderDelegate.java:99)
[2021-06-14T14:58:06.056Z] 	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContext(DefaultCacheAwareContextLoaderDelegate.java:124)
[2021-06-14T14:58:06.056Z] 	at org.springframework.test.context.support.DefaultTestContext.getApplicationContext(DefaultTestContext.java:123)
[2021-06-14T14:58:06.056Z] 	at io.cucumber.spring.TestContextAdaptor.createTestContextManagerAdaptor(TestContextAdaptor.java:32)
[2021-06-14T14:58:06.056Z] 	at io.cucumber.spring.SpringFactory.start(SpringFactory.java:146)
[2021-06-14T14:58:06.056Z] 	at io.cucumber.core.runner.Runner.buildBackendWorlds(Runner.java:165)
[2021-06-14T14:58:06.056Z] 	at io.cucumber.core.runner.Runner.runPickle(Runner.java:62)
[2021-06-14T14:58:06.056Z] 	at io.cucumber.junit.PickleRunners$NoStepDescriptions.run(PickleRunners.java:149)
[2021-06-14T14:58:06.056Z] 	at io.cucumber.junit.FeatureRunner.runChild(FeatureRunner.java:83)
[2021-06-14T14:58:06.056Z] 	at io.cucumber.junit.FeatureRunner.runChild(FeatureRunner.java:24)
[2021-06-14T14:58:06.056Z] 	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
[2021-06-14T14:58:06.056Z] 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
[2021-06-14T14:58:06.056Z] 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
[2021-06-14T14:58:06.056Z] 	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
[2021-06-14T14:58:06.056Z] 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
[2021-06-14T14:58:06.056Z] 	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
[2021-06-14T14:58:06.056Z] 	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
[2021-06-14T14:58:06.056Z] 	at io.cucumber.junit.Cucumber.runChild(Cucumber.java:185)
[2021-06-14T14:58:06.056Z] 	at io.cucumber.junit.Cucumber.runChild(Cucumber.java:83)
[2021-06-14T14:58:06.056Z] 	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
[2021-06-14T14:58:06.056Z] 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
[2021-06-14T14:58:06.056Z] 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
[2021-06-14T14:58:06.056Z] 	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
[2021-06-14T14:58:06.056Z] 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
[2021-06-14T14:58:06.056Z] 	at io.cucumber.junit.Cucumber$RunCucumber.evaluate(Cucumber.java:219)
[2021-06-14T14:58:06.056Z] 	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
[2021-06-14T14:58:06.056Z] 	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
[2021-06-14T14:58:06.056Z] 	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
[2021-06-14T14:58:06.056Z] 	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
[2021-06-14T14:58:06.056Z] 	at org.junit.vintage.engine.execution.RunnerExecutor.execute(RunnerExecutor.java:43)
[2021-06-14T14:58:06.056Z] 	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
[2021-06-14T14:58:06.056Z] 	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
[2021-06-14T14:58:06.056Z] 	at java.util.Iterator.forEachRemaining(Iterator.java:116)
[2021-06-14T14:58:06.056Z] 	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
[2021-06-14T14:58:06.056Z] 	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
[2021-06-14T14:58:06.056Z] 	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
[2021-06-14T14:58:06.056Z] 	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
[2021-06-14T14:58:06.056Z] 	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
[2021-06-14T14:58:06.056Z] 	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[2021-06-14T14:58:06.056Z] 	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
[2021-06-14T14:58:06.056Z] 	at org.junit.vintage.engine.VintageTestEngine.executeAllChildren(VintageTestEngine.java:82)
[2021-06-14T14:58:06.056Z] 	at org.junit.vintage.engine.VintageTestEngine.execute(VintageTestEngine.java:73)
[2021-06-14T14:58:06.056Z] 	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:248)
[2021-06-14T14:58:06.056Z] 	at org.junit.platform.launcher.core.DefaultLauncher.lambda$execute$5(DefaultLauncher.java:211)
[2021-06-14T14:58:06.056Z] 	at org.junit.platform.launcher.core.DefaultLauncher.withInterceptedStreams(DefaultLauncher.java:226)
[2021-06-14T14:58:06.056Z] 	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:199)
[2021-06-14T14:58:06.056Z] 	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:132)
[2021-06-14T14:58:06.056Z] 	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invokeAllTests(JUnitPlatformProvider.java:150)
[2021-06-14T14:58:06.057Z] 	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invoke(JUnitPlatformProvider.java:124)
[2021-06-14T14:58:06.057Z] 	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
[2021-06-14T14:58:06.057Z] 	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
[2021-06-14T14:58:06.057Z] 	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
[2021-06-14T14:58:06.057Z] 	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
[2021-06-14T14:58:06.057Z] Caused by: java.nio.file.AccessDeniedException: target/embeddedCassandra
[2021-06-14T14:58:06.057Z] 	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:84)
[2021-06-14T14:58:06.057Z] 	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
[2021-06-14T14:58:06.057Z] 	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
[2021-06-14T14:58:06.057Z] 	at sun.nio.fs.UnixFileStore.readAttributes(UnixFileStore.java:111)
[2021-06-14T14:58:06.057Z] 	at sun.nio.fs.UnixFileStore.getTotalSpace(UnixFileStore.java:118)
[2021-06-14T14:58:06.057Z] 	at org.apache.cassandra.io.util.FileUtils$SafeFileStore.getTotalSpace(FileUtils.java:744)
[2021-06-14T14:58:06.057Z] 	at org.apache.cassandra.config.DatabaseDescriptor.applySimpleConfig(DatabaseDescriptor.java:493)
[2021-06-14T14:58:06.057Z] 	... 85 common frames omitted

``

**Comment by claudioabudio** [comment]
so the issue happens within the call to : `` 
      DatabaseDescriptor.daemonInitialization();
            cleanupAndLeaveDirs();
            CountDownLatch startupLatch = new CountDownLatch(1);
            ExecutorService executor = Executors.newSingleThreadExecutor();
            executor.execute(() -> {
                cassandraDaemon = new CassandraDaemon();
                cassandraDaemon.activate();
                startupLatch.countDown();
            });
``

**Comment by jsevellec** [comment]
**Cause.** Same root cause as #316: the commitlog disk-space check ran against `target/embeddedCassandra`, which `tmpDir` never actually moved.

**Fixed in #345.** `tmpDir` now relocates every storage directory, the default is under `java.io.tmpdir`, and `cleanup()` no longer throws on a missing directory (f148112).

Fixed on `main` and shipping in **5.0.0**, which is not on Maven Central yet — Central still has 4.3.1.0. Docs: https://github.com/jsevellec/cassandra-unit/tree/main/docs

Closing as fixed; sorry this took so long.
