### ISSUE TITLE
ClassNotFoundException: org.apache.cassandra.thrift.Cassandra$Iface

### ISSUE THREAD

**Issue by amichair** [jsevellec/cassandra-unit#331]
When attempting to upgrade to 3.11.11, the following exception is thrown (same code in 3.11.10 works fine):

Exception (java.lang.NoClassDefFoundError) encountered during startup: org/apache/cassandra/thrift/Cassandra$Iface
java.lang.NoClassDefFoundError: org/apache/cassandra/thrift/Cassandra$Iface
        at org.apache.cassandra.service.CassandraDaemon.initializeClientTransports(CassandraDaemon.java:450)
        at org.apache.cassandra.service.CassandraDaemon.setup(CassandraDaemon.java:438)
        at org.apache.cassandra.service.CassandraDaemon.activate(CassandraDaemon.java:633)
        at org.cassandraunit.utils.EmbeddedCassandraServerHelper.lambda$startEmbeddedCassandra$1(EmbeddedCassandraServerHelper.java:152)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: org.apache.cassandra.thrift.Cassandra$Iface
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 7 more

btw is this project abandoned?

**Comment by elahrvivaz** [comment]
I had this same issue and was able to resolve it by adding `org.apache.cassandra:cassandra-thrift:3.11.14` as a test dependency

**Comment by jsevellec** [comment]
**Cause.** `cassandra-thrift` was on the classpath in some configurations but not others.

**Fixed in #345.** Thrift is gone: removed from Cassandra in 4.0, and `cassandra-thrift` is not published past the 3.11 line, so both it and `libthrift` were dropped (85e4dae).

Fixed on `main` and shipping in **5.0.0**, which is not on Maven Central yet — Central still has 4.3.1.0. Docs: https://github.com/jsevellec/cassandra-unit/tree/main/docs

Closing as fixed; sorry this took so long.
