### ISSUE TITLE
CU hangs on CommitLog creation with Java 17 - Update cassandra-all to 4.0.1 to support Java 17

### ISSUE THREAD

**Issue by miikeat** [jsevellec/cassandra-unit#332]
When I try to run cassandra-unit in java17 it hangs in AbrstactCommitLogSegmentManager upon calling create segment.
After some digging I assume cassandra-all 3.1.1 does not support Java 17.
I tried to update the dependency but the yaml files aren't compatible.

I would be really nice to use this library! Are there any plans to switch cassandra-all to V4?

**Comment by markkolich** [comment]
Same problem here &ndash; `cassandra-unit:4.3.1.0` on Java 17 hangs at:

```
"main" #1 prio=5 os_prio=31 cpu=1671.37ms elapsed=871.08s tid=0x00007fc89c015200 nid=0x1403 waiting on condition  [0x0000700008945000]
   java.lang.Thread.State: WAITING (parking)
	at jdk.internal.misc.Unsafe.park(java.base@17.0.5/Native Method)
	at java.util.concurrent.locks.LockSupport.park(java.base@17.0.5/LockSupport.java:341)
	at org.apache.cassandra.utils.concurrent.WaitQueue$AbstractSignal.awaitUninterruptibly(WaitQueue.java:280)
	at org.apache.cassandra.db.commitlog.AbstractCommitLogSegmentManager.awaitAvailableSegment(AbstractCommitLogSegmentManager.java:262)
	at org.apache.cassandra.db.commitlog.AbstractCommitLogSegmentManager.advanceAllocatingFrom(AbstractCommitLogSegmentManager.java:236)
	at org.apache.cassandra.db.commitlog.AbstractCommitLogSegmentManager.start(AbstractCommitLogSegmentManager.java:153)
	at org.apache.cassandra.db.commitlog.CommitLog.start(CommitLog.java:110)
	at org.apache.cassandra.db.commitlog.CommitLog.construct(CommitLog.java:83)
	at org.apache.cassandra.db.commitlog.CommitLog.<clinit>(CommitLog.java:64)
	at org.cassandraunit.utils.EmbeddedCassandraServerHelper.cleanupAndLeaveDirs(EmbeddedCassandraServerHelper.java:338)
	at org.cassandraunit.utils.EmbeddedCassandraServerHelper.startEmbeddedCassandra(EmbeddedCassandraServerHelper.java:147)
	at org.cassandraunit.utils.EmbeddedCassandraServerHelper.startEmbeddedCassandra(EmbeddedCassandraServerHelper.java:108)
	at org.cassandraunit.utils.EmbeddedCassandraServerHelper.startEmbeddedCassandra(EmbeddedCassandraServerHelper.java:88)
	at org.cassandraunit.utils.EmbeddedCassandraServerHelper.startEmbeddedCassandra(EmbeddedCassandraServerHelper.java:80)
	at org.cassandraunit.utils.EmbeddedCassandraServerHelper.startEmbeddedCassandra(EmbeddedCassandraServerHelper.java:76)
	at ***.***.CassandraUnitConnection.createCassandraUnitSession(CassandraUnitConnection.java:61)
```

Works fine on Java 11.

Haven't yet found a way around this.

**Comment by munepom** [comment]
I'm in trouble too... 😢

**Comment by munepom** [comment]
Apparently it is better to use Testcontainer.
https://www.testcontainers.org/

**Comment by jsevellec** [comment]
**Cause.** `cassandra-all` 3.11.5 predates JDK 17 support, so startup hung.

**Fixed in #345.** Cassandra 5.0.8 and JDK 17 (85e4dae) — the version you asked for, and then some. Note the surefire `argLine` requirement described in the getting-started guide; without those JVM flags the fork dies during startup.

Fixed on `main` and shipping in **5.0.0**, which is not on Maven Central yet — Central still has 4.3.1.0. Docs: https://github.com/jsevellec/cassandra-unit/tree/main/docs

Closing as fixed; sorry this took so long.
