### ISSUE TITLE
Windows 10: Expecting URI in variable

### ISSUE THREAD

**Issue by JukkaOravasaari** [jsevellec/cassandra-unit#335]
cassandra-unit: **4.3.1.0** (https://mvnrepository.com/artifact/org.cassandraunit/cassandra-unit/4.3.1.0)
OS: Windows 10
openjdk version "1.8.0_322"
OpenJDK Runtime Environment (Temurin)(build 1.8.0_322-b06)
OpenJDK 64-Bit Server VM (Temurin)(build 25.322-b06, mixed mode)

Embedded Cassandra startup in Scala:

```
    EmbeddedCassandraServerHelper.startEmbeddedCassandra(
      "/cassandra.yaml",
      60000L
    )
```

Error:

```
[info]   org.apache.cassandra.exceptions.ConfigurationException: Expecting URI in variable: [cassandra.config]. Found[file:/C:\examples\target\embeddedCassandra\cassandra.yaml]. Please prefix the file with [file:\\\] for local files and [file:\\<server>\] for remote files. If you are executing this from an external tool, it needs to set Config.setClientMode(true) to avoid loading configuration.
[info]   at org.apache.cassandra.config.YamlConfigurationLoader.getStorageConfigURL(YamlConfigurationLoader.java:84)
[info]   at org.apache.cassandra.config.YamlConfigurationLoader.loadConfig(YamlConfigurationLoader.java:104)
[info]   at org.apache.cassandra.config.DatabaseDescriptor.loadConfig(DatabaseDescriptor.java:301)
[info]   at org.apache.cassandra.config.DatabaseDescriptor.daemonInitialization(DatabaseDescriptor.java:177)
[info]   at org.apache.cassandra.config.DatabaseDescriptor.daemonInitialization(DatabaseDescriptor.java:162)
[info]   at org.cassandraunit.utils.EmbeddedCassandraServerHelper.startEmbeddedCassandra(EmbeddedCassandraServerHelper.java:145)
[info]   at org.cassandraunit.utils.EmbeddedCassandraServerHelper.startEmbeddedCassandra(EmbeddedCassandraServerHelper.java:108)
[info]   at org.cassandraunit.utils.EmbeddedCassandraServerHelper.startEmbeddedCassandra(EmbeddedCassandraServerHelper.java:88)
```

There is no such issue when running cassandra-unit in Linux.

**Comment by jsevellec** [comment]
**Cause.** The Cassandra config path was turned into a URI by string concatenation, choosing between `file://` and `file:/` on a leading-slash test, which is wrong for Windows drive letters.

**Fixed in #345.** The path is now converted with `file.toPath().toUri()`, which produces a correct URI on every platform.

Fixed on `main` and shipping in **5.0.0**, which is not on Maven Central yet — Central still has 4.3.1.0. Docs: https://github.com/jsevellec/cassandra-unit/tree/main/docs

Closing as fixed; sorry this took so long.
