### ISSUE TITLE
OOM - unable to create new native thread

### ISSUE THREAD

**Issue by prowave** [jsevellec/cassandra-unit#74]
Jeremy,

I am on the Spring-Data-Cassandra team and we are making good use of cassandra-unit.  Nice work!

We have an issue that only occurs on Macs, and we have a large number of test cases.  As you can imagine, all of our integration tests use cassandra-unit. :)

It seems almost like each test doesn't thoroughly clean up after itself before forking a new cassandra instance.  We have tried with and without forking and still get the error.  Thanks for the help.

Have you seen this error before in your testing?

If not, we can help reproduce it.

java.lang.OutOfMemoryError: unable to create new native thread
    at java.lang.Thread.start0(Native Method)
    at java.lang.Thread.start(Thread.java:713)
    at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:949)
    at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1371)
    at org.jboss.netty.util.internal.DeadLockProofWorker.start(DeadLockProofWorker.java:38)
    at org.jboss.netty.channel.socket.nio.AbstractNioSelector.openSelector(AbstractNioSelector.java:343)
    at org.jboss.netty.channel.socket.nio.AbstractNioSelector.<init>(AbstractNioSelector.java:95)
    at org.jboss.netty.channel.socket.nio.AbstractNioWorker.<init>(AbstractNioWorker.java:53)
    at org.jboss.netty.channel.socket.nio.NioWorker.<init>(NioWorker.java:45)
    at org.jboss.netty.channel.socket.nio.NioWorkerPool.createWorker(NioWorkerPool.java:45)
    at org.jboss.netty.channel.socket.nio.NioWorkerPool.createWorker(NioWorkerPool.java:28)
    at org.jboss.netty.channel.socket.nio.AbstractNioWorkerPool.newWorker(AbstractNioWorkerPool.java:99)
    at org.jboss.netty.channel.socket.nio.AbstractNioWorkerPool.init(AbstractNioWorkerPool.java:69)
    at org.jboss.netty.channel.socket.nio.NioWorkerPool.<init>(NioWorkerPool.java:39)
    at org.jboss.netty.channel.socket.nio.NioWorkerPool.<init>(NioWorkerPool.java:33)
    at org.jboss.netty.channel.socket.nio.NioClientSocketChannelFactory.<init>(NioClientSocketChannelFactory.java:151)
    at org.jboss.netty.channel.socket.nio.NioClientSocketChannelFactory.<init>(NioClientSocketChannelFactory.java:116)
    at com.datastax.driver.core.Connection$Factory.<init>(Connection.java:406)
    at com.datastax.driver.core.Connection$Factory.<init>(Connection.java:417)
    at com.datastax.driver.core.Cluster$Manager.<init>(Cluster.java:787)
    at com.datastax.driver.core.Cluster$Manager.<init>(Cluster.java:739)
    at com.datastax.driver.core.Cluster.<init>(Cluster.java:80)
    at com.datastax.driver.core.Cluster.<init>(Cluster.java:67)
    at com.datastax.driver.core.Cluster$Builder.build(Cluster.java:708)
    at org.springframework.cassandra.test.integration.AbstractEmbeddedCassandraIntegrationTest.cluster(AbstractEmbeddedCassandraIntegrationTest.java:68)
    at org.springframework.cassandra.test.integration.AbstractEmbeddedCassandraIntegrationTest.connect(AbstractEmbeddedCassandraIntegrationTest.java:73)
    at org.springframework.cassandra.test.integration.AbstractEmbeddedCassandraIntegrationTest.<init>(AbstractEmbeddedCassandraIntegrationTest.java:32)
    at org.springframework.cassandra.test.integration.core.template.CassandraOperationsTest.<init>(CassandraOperationsTest.java:68)

**Comment by ColinMc** [comment]
My company is also running into this issue. We are also using Spring Data Cassandra and using Spring Cassandra Unit.

**Comment by justinhrobbins** [comment]
I am seeing the same issue on OSX.  Strangely, it runs without error on another OSX machine.

**Comment by jsevellec** [comment]
Hey guys,

Is this still an issue?

**Comment by jsevellec** [comment]
Old, and no reproduction. `OutOfMemoryError: unable to create new native thread` is usually environmental (thread/process ulimits) rather than a library bug, though the embedded server does start a lot of threads. If this still reproduces on 5.0.0, a thread dump would help.

Keeping this open. (Triage pass after the Cassandra 5.0 / JDK 17 modernization, #345.)

**Comment by jsevellec** [comment]
Closing as not reproducible. `OutOfMemoryError: unable to create new native thread` is a process limit being hit — on macOS typically `ulimit -u` or the kernel's per-process thread cap — rather than a leak this library can fix, and it was only ever seen on some machines and not others, which fits that. The embedded server does start many threads, so the practical mitigation is fewer concurrent surefire forks (`forkCount`) or a higher limit. If it reproduces on 5.x, a thread dump at the point of failure would show whether threads are accumulating across tests.
